var country_list = {
    // USA
    usa: [
        ['AL', 'Alabama', 'Montgomery'],
        ['AK', 'Alaska', 'Juneau'],
        ['AZ', 'Arizona', 'Phoenix'],
        ['AR', 'Arkansas', 'Little Rock'],
        ['CA', 'California', 'Sacramento'],
        ['CO', 'Colorado', 'Denver'],
        ['CT', 'Connecticut', 'Hartford'],
        ['DE', 'Delaware', 'Dover'],
        ['DC', 'District of Columbia', 'Washington DC'],
        ['FL', 'Florida', 'Tallahassee'],
        ['GA', 'Georgia', 'Atlanta'],
        ['HI', 'Hawaii', 'Honolulu'],
        ['ID', 'Idaho', 'Boise'],
        ['IL', 'Illinois', 'Springfield'],
        ['IN', 'Indiana', 'Indianapolis'],
        ['IA', 'Iowa', 'Des Moines'],
        ['KS', 'Kansas', 'Topeka'],
        ['KY', 'Kentucky', 'Frankfort'],
        ['LA', 'Louisiana', 'Baton Rouge'],
        ['ME', 'Maine', 'Augusta'],
        ['MD', 'Maryland', 'Annapolis'],
        ['MA', 'Massachusetts', 'Boston'],
        ['MI', 'Michigan', 'Lansing'],
        ['MN', 'Minnesota', 'Saint Paul'],
        ['MS', 'Mississippi', 'Jackson'],
        ['MO', 'Missouri', 'Jefferson City'],
        ['MT', 'Montana', 'Helena'],
        ['NE', 'Nebraska', 'Lincoln'],
        ['NV', 'Nevada', 'Carson City'],
        ['NH', 'New Hampshire', 'Concord'],
        ['NJ', 'New Jersey', 'Trenton'],
        ['NM', 'New Mexico', 'Santa Fe'],
        ['NY', 'New York', 'Albany'],
        ['NC', 'North Carolina', 'Rayleigh'],
        ['ND', 'North Dakota', 'Bismarck'],
        ['OH', 'Ohio', 'Columbus'],
        ['OK', 'Oklahoma', 'Oklahoma City'],
        ['OR', 'Oregon', 'Salem'],
        ['PA', 'Pennsylvania', 'Harrisburg'],
        ['RI', 'Rhode Island', 'Providence'],
        ['SC', 'South Carolina', 'Columbia'],
        ['SD', 'South Dakota', 'Pierre'],
        ['TN', 'Tennessee', 'Nashville'],
        ['TX', 'Texas', 'Austin'],
        ['UT', 'Utah', 'Salt Lake City'],
        ['VT', 'Vermont', 'Montpelier'],
        ['VA', 'Virginia', 'Richmond'],
        ['WA', 'Washington', 'Olympia'],
        ['WV', 'West Virginia', 'Charleston'],
        ['WI', 'Wisconsin', 'Madison'],
        ['WY', 'Wyoming', 'Cheyenne']
    ],

    // CANADA
    can: [
        ['10', 'Newfoundland', null],
        ['11', 'Prince Edward Island', null],
        ['12', 'Nova Scotia', null],
        ['13', 'New Brunswick', null],
        ['24', 'Quebec', null],
        ['35', 'Ontario', null],
        ['46', 'Manitoba', null],
        ['47', 'Saskatchewan', null],
        ['48', 'Alberta', null],
        ['59', 'British Columbia', null],
        ['60', 'Yukon', null],
        ['61', 'Northwest Territories', null],
        ['62', 'Nunavut', null]
    ],

    // RUSSIA
    rus: [
        ['01', 'Адыгея республика', null],
        ['04', 'Алтай республика', null],
        ['22', 'Алтайский край', null],
        ['28', 'Амурская область', null],
        ['29', 'Архангельская область', null],
        ['30', 'Астраханская область', null],
        ['02', 'Башкортостан республика', null],
        ['31', 'Белгородская область', null],
        ['32', 'Брянская область', null],
        ['03', 'Бурятия республика', null],
        ['33', 'Владимирская область', null],
        ['34', 'Волгоградская область', null],
        ['35', 'Вологодская область', null],
        ['36', 'Воронежская область', null],
        ['05', 'Дагестан республика', null],
        ['80', 'Донецкая Народная Республика', null],
        ['79', 'Еврейская автономная область', null],
        ['75', 'Забайкальский край', null],
        ['85', 'Запорожская область', null],
        ['37', 'Ивановская область', null],
        ['06', 'Ингушетия республика', null],
        ['38', 'Иркутская область', null],
        ['07', 'Кабардино-Балкарская республика', null],
        ['09', 'Карачаево-Черкесская республика', null],
        ['39', 'Калининградская область', null],
        ['08', 'Калмыкия республика', null],
        ['40', 'Калужская область', null],
        ['41', 'Камчатский край', null],
        ['10', 'Карелия республика', null],
        ['42', 'Кемеровская область', null],
        ['43', 'Кировская область', null],
        ['11', 'Коми республика', null],
        ['44', 'Костромская область', null],
        ['23', 'Краснодарский край', null],
        ['24', 'Красноярский край', null],
        ['82', 'Крым республика', null],
        ['45', 'Курганская область', null],
        ['46', 'Курская область', null],
        ['47', 'Ленинградская область', null],
        ['48', 'Липецкая область', null],
        ['81', 'Луганская Народная Республика', null],
        ['49', 'Магаданская область', null],
        ['12', 'Марий Эл республика', null],
        ['50', 'Московская область', null],
        ['77', 'Москва', 'Москва'],
        ['13', 'Мордовия республика', null],
        ['51', 'Мурманская область', null],
        ['83', 'Ненецкий автономный округ', null],
        ['52', 'Нижегородская область', null],
        ['53', 'Новгородская область', null],
        ['54', 'Новосибирская область', null],
        ['55', 'Омская область', null],
        ['56', 'Оренбургская область', null],
        ['57', 'Орловская область', null],
        ['58', 'Пензенская область', null],
        ['59', 'Пермский край', null],
        ['25', 'Приморский край', null],
        ['60', 'Псковская область', null],
        ['61', 'Ростовская область', null],
        ['62', 'Рязанская область', null],
        ['63', 'Самарская область', null],
        ['78', 'Санкт-Петербург', 'Санкт-Петербург'],
        ['64', 'Саратовская область', null],
        ['14', 'Саха (Якутия) республика', null],
        ['65', 'Сахалинская область', null],
        ['66', 'Свердловская область', null],
        ['92', 'Севастополь', 'Севастополь'],
        ['15', 'Северная Осетия-Алания', null],
        ['67', 'Смоленская область', null],
        ['26', 'Ставропольский край', null],
        ['68', 'Тамбовская область', null],
        ['16', 'Татарстан республика', null],
        ['69', 'Тверская область', null],
        ['70', 'Томская область', null],
        ['71', 'Тульская область', null],
        ['72', 'Тюменская область', null],
        ['17', 'Тыва республика', null],
        ['18', 'Удмуртская республика', null],
        ['73', 'Ульяновская область', null],
        ['27', 'Хабаровский край', null],
        ['19', 'Хакасия республика', null],
        ['86', 'Ханты-Мансийский-Югра автономный округ', null],
        ['84', 'Херсонская область', null],
        ['74', 'Челябинская область', null],
        ['20', 'Чеченская республика', null],
        ['21', 'Чувашская республика', null],
        ['87', 'Чукотский автономный округ', null],
        ['89', 'Ямало-Ненецкий автономный округ', null],
        ['76', 'Ярославская область', null]
    ],

    // UKRAINE
    ukr: [
        ['01', 'Автономна Республіка Крим', null],
        ['02', 'Вінницька область', null],
        ['03', 'Волинська область', null],
        ['04', 'Дніпропетровська область', null],
        ['05', 'Донецька область', null],
        ['06', 'Житомирська область', null],
        ['07', 'Закарпатська область', null],
        ['08', 'Запорізька область', null],
        ['09', 'Івано-Франківська область', null],
        ['10', 'Київська область', null],
        ['11', 'місто Київ', null],
        ['12', 'Кіровоградська область', null],
        ['13', 'Луганська область', null],
        ['14', 'Львівська область', null],
        ['15', 'Миколаївська область', null],
        ['16', 'Одеська область', null],
        ['17', 'Полтавська область', null],
        ['18', 'Рівненська область', null],
        ['19', 'Сумська область', null],
        ['20', 'Тернопільська область', null],
        ['21', 'Харківська область', null],
        ['22', 'Херсонська область', null],
        ['23', 'Хмельницька область', null],
        ['24', 'Черкаська область', null],
        ['25', 'Чернігівська область', null],
        ['26', 'Чернівецька область', null]
    ],

    // BELARUS
    blr: [
        ['01', 'Брэсцкая вобласць', 'Брэст'],
        ['02', 'Віцебская вобласць', 'Віцебск'],
        ['03', 'Гомельская вобласць', 'Гомель'],
        ['04', 'Гродзенская вобласць', 'Гродна'],
        ['05', 'Мінская вобласць', 'Мінск'],
        ['06', 'Магілёўская вобласць', 'Магілёў'],
        ['07', 'Мінск', 'Мінск']
    ],

    // KAZAKHSTAN
    kaz: [
        ['01', 'Астана', 'Астана'],
        ['02', 'Алматы', 'Алматы'],
        ['03', 'Ақмола облысы', 'Көкшетау'],
        ['04', 'Ақтөбе облысы', 'Ақтөбе'],
        ['05', 'Алматы облысы', 'Қонаев'],
        ['06', 'Атырау облысы', 'Атырау'],
        ['07', 'Батыс Қазақстан облысы', 'Орал'],
        ['08', 'Жамбыл облысы', 'Тараз'],
        ['09', 'Қарағанды облысы', 'Қарағанды'],
        ['10', 'Қостанай облысы', 'Қостанай'],
        ['11', 'Қызылорда облысы', 'Қызылорда'],
        ['12', 'Маңғыстау облысы', 'Ақтау'],
        ['13', 'Түркістан облысы', 'Түркістан'],
        ['14', 'Павлодар облысы', 'Павлодар'],
        ['15', 'Солтүстік Қазақстан облысы', 'Петропавл'],
        ['16', 'Шығыс Қазақстан облысы', 'Өскемен'],
        ['17', 'Шымкент', 'Шымкент'],
        ['18', 'Абай облысы', 'Семей'],
        ['19', 'Жетісу облысы', 'Талдықорған'],
        ['20', 'Ұлытау облысы', 'Жезқазған']
    ],

    // ARMENIA
    arm: [
        ['01', 'Арагацотнская область', 'Аштарак'],
        ['02', 'Араратская область', 'Арташат'],
        ['03', 'Армавирская область', 'Армавир'],
        ['04', 'Вайоцдзорская область', 'Ехегнадзор'],
        ['05', 'Гехаркуникская область', 'Гавар'],
        ['06', 'Котайкская область', 'Раздан'],
        ['07', 'Лорийская область', 'Ванадзор'],
        ['08', 'Сюникская область', 'Капан'],
        ['09', 'Тавушская область', 'Иджеван'],
        ['10', 'Ширакская область', 'Гюмри'],
        ['11', 'Ереван', 'Ереван']
    ],

    // GEORGIA
    geo: [
        ['GE-AB', 'Абхазская Автономная Республика', 'Сухуми'],
        ['GE-SZ', 'Самегрело-Верхняя Сванетия', 'Зугдиди'],
        ['GE-GU', 'Гурия', 'Озургети'],
        ['GE-AJ', 'Аджарская Автономная Республика', 'Батуми'],
        ['GE-RL', 'Рача-Лечхуми и Нижняя Сванетия', 'Амбролаури'],
        ['GE-IM', 'Имеретия', 'Кутаиси'],
        ['GE-SJ', 'Самцхе-Джавахетия', 'Ахалцихе'],
        ['GE-SK', 'Шида-Картли', 'Гори'],
        ['GE-MM', 'Мцхета-Мтианети', 'Мцхета'],
        ['GE-KK', 'Квемо-Картли', 'Рустави'],
        ['GE-KA', 'Кахетия', 'Телави'],
        ['GE-TB', 'Тбилиси', 'Тбилиси']
    ],

    // CHINA
    chn: [
        ['11', 'Beijing', null],
        ['12', 'Tianjin', null],
        ['13', 'Hebei', null],
        ['14', 'Shanxi', null],
        ['21', 'Liaoning', null],
        ['15', 'Inner Mongolia', null],
        ['22', 'Jilin', null],
        ['23', 'Heilongjiang', null],
        ['34', 'Anhui', null],
        ['33', 'Zhejiang', null],
        ['36', 'Jiangxi', null],
        ['31', 'Shanghai', null],
        ['35', 'Fujian', null],
        ['32', 'Jiangsu', null],
        ['37', 'Shandong', null],
        ['46', 'Hainan', null],
        ['42', 'Hubei', null],
        ['43', 'Hunan', null],
        ['41', 'Henan', null],
        ['44', 'Guangdong', null],
        ['45', 'Guangxi', null],
        ['50', 'Chongqing', null],
        ['51', 'Sichuan', null],
        ['61', 'Shaanxi', null],
        ['53', 'Yunnan', null],
        ['54', 'Xizang', null],
        ['62', 'Gansu', null],
        ['52', 'Guizhou', null],
        ['64', 'Ningxia', null],
        ['63', 'Qinghai', null],
        ['65', 'Xinjiang', null]
    ],

    // INDIA
    ind: [
        ['37', 'Andhra Pradesh', 'Amaravati'],
        ['12', 'Arunachal Pradesh', 'Itanagar'],
        ['18', 'Assam', 'Dispur'],
        ['10', 'Bihar', 'Patna'],
        ['22', 'Chhattisgarh', 'Raipur'],
        ['7', 'Delhi', 'Delhi'],
        ['30', 'Goa', 'Panaji'],
        ['24', 'Gujarat', 'Gandhinagar'],
        ['6', 'Haryana', 'Chandigarh'],
        ['2', 'Himachal Pradesh', 'Shimla'],
        ['1', 'Jammu and Kashmir', 'Srinagar'],
        ['20', 'Jharkhand', 'Ranchi'],
        ['29', 'Karnataka', 'Bengaluru'],
        ['32', 'Kerala', 'Thiruvananthapuram'],
        ['31', 'Lakshadweep Islands', 'Kavaratti'],
        ['23', 'Madhya Pradesh', 'Bhopal'],
        ['27', 'Maharashtra', 'Mumbai'],
        ['14', 'Manipur', 'Imphal'],
        ['17', 'Meghalaya', 'Shillong'],
        ['15', 'Mizoram', 'Aizawl'],
        ['13', 'Nagaland', 'Kohima'],
        ['21', 'Odisha', 'Bhubaneswar'],
        ['34', 'Pondicherry', 'Pondicherry'],
        ['3', 'Punjab', 'Chandigarh'],
        ['8', 'Rajasthan', 'Jaipur'],
        ['11', 'Sikkim', 'Gangtok'],
        ['33', 'Tamil Nadu', 'Chennai'],
        ['36', 'Telangana', 'Hyderabad'],
        ['16', 'Tripura', 'Agartala'],
        ['9', 'Uttar Pradesh', 'Lucknow'],
        ['5', 'Uttarakhand', 'Dehradun'],
        ['19', 'West Bengal', 'Kolkata']
    ],

    // AUSTRALIA
    aus: [
        ['1', 'New South Wales', 'Sydney'],
        ['2', 'Victoria', 'Melbourne'],
        ['3', 'Queensland', 'Brisbane'],
        ['4', 'South Australia', 'Adelaide'],
        ['5', 'Western Australia', 'Perth'],
        ['6', 'Tasmania', 'Hobart'],
        ['7', 'Northern Territory', 'Darwin'],
        ['8', 'Australian Capital Territory', 'Canberra'],
        ['9', 'Other Territories', null]
    ],

    // GERMANY
    deu: [
        ['01', 'Schleswig-Holstein', null],
        ['02', 'Hamburg', null],
        ['03', 'Niedersachsen', null],
        ['04', 'Bremen', null],
        ['05', 'Nordrhein-Westfalen', null],
        ['06', 'Hessen', null],
        ['07', 'Rheinland-Pfalz', null],
        ['08', 'Baden-Württemberg', null],
        ['09', 'Bayern', null],
        ['10', 'Saarland', null],
        ['11', 'Berlin', null],
        ['12', 'Brandenburg', null],
        ['13', 'Mecklenburg-Vorpommern', null],
        ['14', 'Sachsen', null],
        ['15', 'Sachsen-Anhalt', null],
        ['16', 'Thueringen', null]
    ],

    // BELGIUM
    bel: [
        ['11', 'Antwerpen', null],
        ['12', 'Mechelen', null],
        ['13', 'Turnhout', null],
        ['21', 'Brussel-Hoofdstad', null],
        ['23', 'Halle-Vilvoorde', null],
        ['24', 'Leuven', null],
        ['25', 'Nijvel', null],
        ['31', 'Brugge', null],
        ['32', 'Diksmuide', null],
        ['33', 'Ieper', null],
        ['34', 'Kortrijk', null],
        ['35', 'Oostende', null],
        ['36', 'Roeselare', null],
        ['37', 'Tielt', null],
        ['38', 'Veurne', null],
        ['41', 'Aalst', null],
        ['42', 'Dendermonde', null],
        ['43', 'Eeklo', null],
        ['44', 'Gent', null],
        ['45', 'Oudenaarde', null],
        ['46', 'Sint-Niklaas', null],
        ['51', 'Aat', null],
        ['52', 'Charleroi', null],
        ['53', 'Bergen', null],
        ['54', 'Moeskroen', null],
        ['55', 'Zinnik', null],
        ['56', 'Thuin', null],
        ['57', 'Doornik', null],
        ['61', 'Hoei', null],
        ['62', 'Luik', null],
        ['63', 'Verviers', null],
        ['64', 'Borgworm', null],
        ['71', 'Hasselt', null],
        ['72', 'Maaseik', null],
        ['73', 'Tongeren', null],
        ['81', 'Aarlen', null],
        ['82', 'Bastenaken', null],
        ['83', 'Marche-en-Famenne', null],
        ['84', 'Neufchâteau', null],
        ['85', 'Virton', null],
        ['91', 'Dinant', null],
        ['92', 'Namen', null],
        ['93', 'Philippeville', null]
    ],

    // DENMARK
    dnk: [
        ['101', 'København', null],
        ['102', 'Frederiksberg', null],
        ['150', 'Københavns Amt', null],
        ['200', 'Frederiksborg Amt', null],
        ['250', 'Roskilde Amt', null],
        ['300', 'Vestsjællands Amt', null],
        ['350', 'Storstrøms Amt', null],
        ['400', 'Bornholms Amt', null],
        ['420', 'Fyns Amt', null],
        ['500', 'Sønderjyllands Amt', null],
        ['550', 'Ribe Amt', null],
        ['600', 'Vejle Amt', null],
        ['650', 'Ringkøbing Amt', null],
        ['700', 'Århus Amt', null],
        ['760', 'Viborg Amt', null],
        ['800', 'Nordjyllands Amt', null]
    ],

    // FRANCE
    fra: [
        ['01', 'Ain', null],
        ['02', 'Aisne', null],
        ['03', 'Allier', null],
        ['04', 'Alpes-de-Haute-Provence', null],
        ['05', 'Hautes-Alpes', null],
        ['06', 'Alpes-Maritimes', null],
        ['07', 'Ardèche', null],
        ['08', 'Ardennes', null],
        ['09', 'Ariège', null],
        ['10', 'Aube', null],
        ['11', 'Aude', null],
        ['12', 'Aveyron', null],
        ['13', 'Bouches-du-Rhône', null],
        ['14', 'Calvados', null],
        ['15', 'Cantal', null],
        ['16', 'Charente', null],
        ['17', 'Charente-Maritime', null],
        ['18', 'Cher', null],
        ['19', 'Corrèze', null],
        ['21', 'Côte-d\'Or', null],
        ['22', 'Côtes-du-Nord', null],
        ['23', 'Creuse', null],
        ['24', 'Dordogne', null],
        ['25', 'Doubs', null],
        ['26', 'Drôme', null],
        ['27', 'Eure', null],
        ['28', 'Eure-et-Loir', null],
        ['29', 'Finistère', null],
        ['30', 'Gard', null],
        ['31', 'Haute-Garonne', null],
        ['32', 'Gers', null],
        ['33', 'Gironde', null],
        ['34', 'Hérault', null],
        ['35', 'Ille-et-Vilaine', null],
        ['36', 'Indre', null],
        ['37', 'Indre-et-Loire', null],
        ['38', 'Isère', null],
        ['39', 'Jura', null],
        ['40', 'Landes', null],
        ['41', 'Loir-et-Cher', null],
        ['42', 'Loire', null],
        ['43', 'Haute-Loire', null],
        ['44', 'Loire-Atlantique', null],
        ['45', 'Loiret', null],
        ['46', 'Lot', null],
        ['47', 'Lot-et-Garonne', null],
        ['48', 'Lozère', null],
        ['49', 'Maine-et-Loire', null],
        ['50', 'Manche', null],
        ['51', 'Marne', null],
        ['52', 'Haute-Marne', null],
        ['53', 'Mayenne', null],
        ['54', 'Meurthe-et-Moselle', null],
        ['55', 'Meuse', null],
        ['56', 'Morbihan', null],
        ['57', 'Moselle', null],
        ['58', 'Nièvre', null],
        ['59', 'Nord', null],
        ['60', 'Oise', null],
        ['61', 'Orne', null],
        ['62', 'Pas-de-Calais', null],
        ['63', 'Puy-de-Dôme', null],
        ['64', 'Pyrénées-Atlantiques', null],
        ['65', 'Hautes-Pyrénées', null],
        ['66', 'Pyrénées-Orientales', null],
        ['67', 'Bas-Rhin', null],
        ['68', 'Haut-Rhin', null],
        ['69', 'Rhône', null],
        ['70', 'Haute-Saône', null],
        ['71', 'Saône-et-Loire', null],
        ['72', 'Sarthe', null],
        ['73', 'Savoie', null],
        ['74', 'Haute-Savoie', null],
        ['75', 'Ville-de-Paris', null],
        ['76', 'Seine-Maritime', null],
        ['77', 'Seine-et-Marne', null],
        ['78', 'Yvelines', null],
        ['79', 'Deux-Sèvres', null],
        ['80', 'Somme', null],
        ['81', 'Tarn', null],
        ['82', 'Tarn-et-Garonne', null],
        ['83', 'Var', null],
        ['84', 'Vaucluse', null],
        ['85', 'Vendée', null],
        ['86', 'Vienne', null],
        ['87', 'Haute-Vienne', null],
        ['88', 'Vosges', null],
        ['89', 'Yonne', null],
        ['90', 'Territoire-de-Belfort', null],
        ['91', 'Essonne', null],
        ['92', 'Hauts-de-Seine', null],
        ['93', 'Seine-Saint-Denis', null],
        ['94', 'Val-de-Marne', null],
        ['95', 'Val-d\'Oise', null],
        ['99', 'Monaco', null],
        ['2A', 'Corse-du-Sud', null],
        ['2B', 'Haute-Corse', null]
    ],

    // GREECE
    grc: [
        ['01', 'Aitolias Kai Akarnanias', null],
        ['03', 'Voiotia', null],
        ['04', 'Eivoias', null],
        ['05', 'Evritania', null],
        ['06', 'Fthiotida', null],
        ['07', 'Fokida', null],
        ['11', 'Argolidos', null],
        ['12', 'Arkadias', null],
        ['13', 'Ahaia', null],
        ['14', 'Ilia', null],
        ['15', 'Korinthos', null],
        ['16', 'Lakonia', null],
        ['17', 'Messinia', null],
        ['21', 'Zakinthos', null],
        ['22', 'Kerkira (Corfu)', null],
        ['23', 'Kefallonia', null],
        ['24', 'Lefkada', null],
        ['31', 'Arta', null],
        ['32', 'Thesprotia', null],
        ['33', 'Ioannina', null],
        ['34', 'Preveza', null],
        ['41', 'Karditsa', null],
        ['42', 'Larissa', null],
        ['43', 'Magnisias', null],
        ['44', 'Trikala', null],
        ['51', 'Grevena', null],
        ['52', 'Drama', null],
        ['53', 'Imathia', null],
        ['54', 'Thessaloniki', null],
        ['55', 'Kavala', null],
        ['56', 'Kastoria', null],
        ['57', 'Kilkis', null],
        ['58', 'Kozani', null],
        ['59', 'Pela', null],
        ['61', 'Pieria', null],
        ['62', 'Seres', null],
        ['63', 'Florina', null],
        ['64', 'Halkida', null],
        ['65', 'Agion Opos', null],
        ['71', 'Evros', null],
        ['72', 'Xanthi', null],
        ['73', 'Rodopi', null],
        ['81', 'Dodekanissa (Dodecanese)', null],
        ['82', 'Kiklades (Cyclades)', null],
        ['83', 'Lesvos', null],
        ['84', 'Samos', null],
        ['85', 'Hios', null],
        ['91', 'Iraklio', null],
        ['92', 'Lasithioi', null],
        ['93', 'Rethimno', null],
        ['94', 'Hania', null],
        ['A1', 'Athina (Athens)', null],
        ['A2', 'Anatoliki Attiki', null],
        ['A3', 'Ditiki Attiki', null],
        ['A4', 'Peiria', null]
    ],

    // INDONESIA
    idn: [
        ['11', 'Nanggroe Aceh Darussalam', null],
        ['12', 'Sumatera Utara', null],
        ['13', 'Sumatera Barat', null],
        ['14', 'Riau', null],
        ['15', 'Jambi', null],
        ['16', 'Sumatera Selatan', null],
        ['17', 'Bengkulu', null],
        ['18', 'Lampung', null],
        ['19', 'Kepulauan Bangka Belitung', null],
        ['21', 'Kepulauan Riau', null],
        ['31', 'DKI Jakarta', null],
        ['32', 'Jawa Barat', null],
        ['33', 'Jawa Tengah', null],
        ['34', 'DI Yogyakarta', null],
        ['35', 'Jawa Timur', null],
        ['36', 'Banten', null],
        ['51', 'Bali', null],
        ['52', 'Nusa Tenggara Barat', null],
        ['53', 'Nusa Tenggara Timur', null],
        ['61', 'Kalimantan Barat', null],
        ['62', 'Kalimantan Tengah', null],
        ['63', 'Kalimantan Selatan', null],
        ['64', 'Kalimantan Timur', null],
        ['71', 'Sulawesi Utara', null],
        ['72', 'Sulawesi Tengah', null],
        ['73', 'Sulawesi Selatan', null],
        ['74', 'Sulawesi Tenggara', null],
        ['75', 'Gorontalo', null],
        ['76', 'Sulawesi Barat', null],
        ['81', 'Maluku', null],
        ['82', 'Maluku Utara', null],
        ['91', 'Papua Barat', null],
        ['94', 'Papua', null]
    ],

    // IRELAND
    irl: [
        ['01', 'Carlow', null],
        ['02', 'Dublin County Borough', null],
        ['03', 'South Dublin', null],
        ['04', 'Fingal', null],
        ['05', 'Dun Laoghaire-Rathdown', null],
        ['06', 'Kildare', null],
        ['07', 'Kilkenny', null],
        ['08', 'Laoighis', null],
        ['09', 'Longford', null],
        ['10', 'Louth', null],
        ['11', 'Meath', null],
        ['12', 'Offaly', null],
        ['13', 'Westmeath', null],
        ['14', 'Wexford', null],
        ['15', 'Wicklow', null],
        ['16', 'Clare', null],
        ['18', 'Cork County Borough', null],
        ['19', 'Cork', null],
        ['20', 'Kerry', null],
        ['22', 'Limerick County Borough', null],
        ['23', 'Limerick', null],
        ['24', 'Tipperary North Riding', null],
        ['25', 'Tipperay South Riding', null],
        ['27', 'Waterford County Borough', null],
        ['28', 'Waterford', null],
        ['29', 'Galway', null],
        ['30', 'Leitrim', null],
        ['31', 'Mayo', null],
        ['32', 'Roscommon', null],
        ['33', 'Sligo', null],
        ['34', 'Cavan', null],
        ['35', 'Donegal', null],
        ['36', 'Monaghan', null],
        ['37', 'Galway County Borough', null]
    ],

    // ISRAEL
    isr: [
        ['01', 'Akko', null],
        ['02', 'Ashqelon', null],
        ['03', 'Beer Sheva', null],
        ['04', 'Gaza Area', null],
        ['05', 'Golan', null],
        ['06', 'Hadera', null],
        ['07', 'Haifa', null],
        ['08', 'Jericho', null],
        ['09', 'Jerusalem', null],
        ['10', 'Kinneret', null],
        ['11', 'Petah Tiqwa', null],
        ['12', 'Ramla', null],
        ['13', 'Rehovot', null],
        ['14', 'Sharon', null],
        ['15', 'Tel Aviv', null],
        ['16', 'Yizreel', null],
        ['17', 'Zefat', null]
    ],

    // ITALY
    ita: [
        ['001', 'Torino', null],
        ['002', 'Vercelli', null],
        ['003', 'Novara', null],
        ['004', 'Cuneo', null],
        ['005', 'Asti', null],
        ['006', 'Alessandria', null],
        ['007', 'Valle d\'Aosta', null],
        ['008', 'Imperia', null],
        ['009', 'Savona', null],
        ['010', 'Genova', null],
        ['011', 'La Spezia', null],
        ['012', 'Varese', null],
        ['013', 'Como', null],
        ['014', 'Sondrio', null],
        ['015', 'Milano', null],
        ['016', 'Bergamo', null],
        ['017', 'Brescia', null],
        ['018', 'Pavia', null],
        ['019', 'Cremona', null],
        ['020', 'Mantova', null],
        ['021', 'Bolzano', null],
        ['022', 'Trento', null],
        ['023', 'Verona', null],
        ['024', 'Vicenza', null],
        ['025', 'Belluno', null],
        ['026', 'Treviso', null],
        ['027', 'Venezia', null],
        ['028', 'Padova', null],
        ['029', 'Rovigo', null],
        ['030', 'Udine', null],
        ['031', 'Gorizia', null],
        ['032', 'Trieste', null],
        ['033', 'Piacenza', null],
        ['034', 'Parma', null],
        ['035', 'Reggio Emilia', null],
        ['036', 'Modena', null],
        ['037', 'Bologna', null],
        ['038', 'Ferrara', null],
        ['039', 'Ravenna', null],
        ['040', 'Forli-Cesena', null],
        ['041', 'Pesaro E Urbino', null],
        ['042', 'Ancona', null],
        ['043', 'Macerata', null],
        ['044', 'Ascoli Piceno', null],
        ['045', 'Massa Carrara', null],
        ['046', 'Lucca', null],
        ['047', 'Pistoia', null],
        ['048', 'Firenze', null],
        ['049', 'Livorno', null],
        ['050', 'Pisa', null],
        ['051', 'Arezzo', null],
        ['052', 'Siena', null],
        ['053', 'Grosseto', null],
        ['054', 'Perugia', null],
        ['055', 'Terni', null],
        ['056', 'Viterbo', null],
        ['057', 'Rieti', null],
        ['058', 'Roma', null],
        ['059', 'Latina', null],
        ['060', 'Frosinone', null],
        ['061', 'Caserta', null],
        ['062', 'Benevento', null],
        ['063', 'Napoli', null],
        ['064', 'Avellino', null],
        ['065', 'Salerno', null],
        ['066', 'L\'Aquila', null],
        ['067', 'Teramo', null],
        ['068', 'Pescara', null],
        ['069', 'Chieti', null],
        ['070', 'Campobasso', null],
        ['071', 'Foggia', null],
        ['072', 'Bari', null],
        ['073', 'Taranto', null],
        ['074', 'Brindisi', null],
        ['075', 'Lecce', null],
        ['076', 'Potenza', null],
        ['077', 'Matera', null],
        ['078', 'Cosenza', null],
        ['079', 'Catanzaro', null],
        ['080', 'Reggio Calabria', null],
        ['081', 'Trapani', null],
        ['082', 'Palermo', null],
        ['083', 'Messina', null],
        ['084', 'Agrigento', null],
        ['085', 'Caltanissetta', null],
        ['086', 'Enna', null],
        ['087', 'Catania', null],
        ['088', 'Ragusa', null],
        ['089', 'Siracusa', null],
        ['090', 'Sassari', null],
        ['091', 'Nuoro', null],
        ['092', 'Cagliari', null],
        ['093', 'Pordenone', null],
        ['094', 'Isernia', null],
        ['095', 'Oristano', null],
        ['096', 'Biella', null],
        ['097', 'Lecco', null],
        ['098', 'Lodi', null],
        ['099', 'Rimini', null],
        ['100', 'Prato', null],
        ['101', 'Crotone', null],
        ['102', 'Vibo Valentia', null],
        ['103', 'Verbano-Cusio-Ossola', null],
        ['104', 'Olbia-Tempio', null],
        ['105', 'Ogliastra', null],
        ['106', 'Medio Campidano', null],
        ['107', 'Carbonia-Iglesias', null],
        ['888', 'Citta del Vaticano', null],
        ['999', 'San Marino', null]
    ],

    // REPUBLIC OF KOREA
    kor: [
        ['11', 'Seoul', null],
        ['21', 'Busan', null],
        ['22', 'Daegu', null],
        ['23', 'Incheon', null],
        ['24', 'Gwangju', null],
        ['25', 'Daejeon', null],
        ['26', 'Ulsan', null],
        ['31', 'Gyeonggi-do', null],
        ['32', 'Gangwon-do', null],
        ['33', 'Chungcheongbuk-do', null],
        ['34', 'Chungcheongnam-do', null],
        ['35', 'Jeollabuk-do', null],
        ['36', 'Jeollanam-do', null],
        ['37', 'Gyeongsangbuk-do', null],
        ['38', 'Gyeongsangnam-do', null],
        ['39', 'Jeju-do', null],
    ],

    // TURKEY
    tur: [
        ['01', 'Adana', null],
        ['02', 'Adýyaman', null],
        ['03', 'Afyonkarahisar', null],
        ['04', 'Aðrý', null],
        ['05', 'Amasya', null],
        ['06', 'Ankara', null],
        ['07', 'Antalya', null],
        ['08', 'Artvin', null],
        ['09', 'Aydýn', null],
        ['10', 'Balýkesir', null],
        ['11', 'Bilecik', null],
        ['12', 'Bingöl', null],
        ['13', 'Bitlis', null],
        ['14', 'Bolu', null],
        ['15', 'Burdur', null],
        ['16', 'Bursa', null],
        ['17', 'Çanakkale', null],
        ['18', 'Çankýrý', null],
        ['19', 'Çorum', null],
        ['20', 'Denizli', null],
        ['21', 'Diyarbakýr', null],
        ['22', 'Edirne', null],
        ['23', 'Elazýð', null],
        ['24', 'Erzincan', null],
        ['25', 'Erzurum', null],
        ['26', 'Eskiþehir', null],
        ['27', 'Gaziantep', null],
        ['28', 'Giresun', null],
        ['29', 'Gümüþhane', null],
        ['30', 'Hakkari', null],
        ['31', 'Hatay', null],
        ['32', 'Isparta', null],
        ['33', 'Mersin', null],
        ['34', 'Ýstanbul', null],
        ['35', 'Ýzmir', null],
        ['36', 'Kars', null],
        ['37', 'Kastamonu', null],
        ['38', 'Kayseri', null],
        ['39', 'Kýrklareli', null],
        ['40', 'Kýrþehir', null],
        ['41', 'Kocaeli', null],
        ['42', 'Konya', null],
        ['43', 'Kütahya', null],
        ['44', 'Malatya', null],
        ['45', 'Manisa', null],
        ['46', 'Kahramanmaraþ', null],
        ['47', 'Mardin', null],
        ['48', 'Muðla', null],
        ['49', 'Muþ', null],
        ['50', 'Nevþehir', null],
        ['51', 'Niðde', null],
        ['52', 'Ordu', null],
        ['53', 'Rize', null],
        ['54', 'Sakarya', null],
        ['55', 'Samsun', null],
        ['56', 'Siirt', null],
        ['57', 'Sinop', null],
        ['58', 'Sivas', null],
        ['59', 'Tekirdað', null],
        ['60', 'Tokat', null],
        ['61', 'Trabzon', null],
        ['62', 'Tunceli', null],
        ['63', 'Þanlýurfa', null],
        ['64', 'Uþak', null],
        ['65', 'Van', null],
        ['66', 'Yozgat', null],
        ['67', 'Zonguldak', null],
        ['68', 'Aksaray', null],
        ['69', 'Bayburt', null],
        ['70', 'Karaman', null],
        ['71', 'Kýrýkkale', null],
        ['72', 'Batman', null],
        ['73', 'Þýrnak', null],
        ['74', 'Bartýn', null],
        ['75', 'Ardahan', null],
        ['76', 'Iðdýr', null],
        ['77', 'Yalova', null],
        ['78', 'Karabük', null],
        ['79', 'Kilis', null],
        ['80', 'Osmaniye', null],
        ['81', 'Düzce', null]
    ],

    // UNITED KINGDOM
    gbr: [
        ['AB', 'Aberdeen', null],
        ['AL', 'St Albans', null],
        ['B', 'Birmingham', null],
        ['BA', 'Bath', null],
        ['BB', 'Blackburn', null],
        ['BD', 'Bradford', null],
        ['BH', 'Bournemouth', null],
        ['BL', 'Bolton', null],
        ['BN', 'Brighton', null],
        ['BR', 'Bromley', null],
        ['BS', 'Bristol', null],
        ['BT', 'Northern Ireland', null],
        ['CA', 'Carlisle', null],
        ['CB', 'Cambridge', null],
        ['CF', 'Cardiff', null],
        ['CH', 'Chester', null],
        ['CM', 'Chelmsford', null],
        ['CO', 'Colchester', null],
        ['CR', 'Croydon', null],
        ['CT', 'Canterbury', null],
        ['CV', 'Coventry', null],
        ['CW', 'Crewe', null],
        ['DA', 'Dartford', null],
        ['DD', 'Dundee', null],
        ['DE', 'Derby', null],
        ['DG', 'Dumfries', null],
        ['DH', 'Durham', null],
        ['DL', 'Darlington', null],
        ['DN', 'Doncaster', null],
        ['DT', 'Dorchester', null],
        ['DY', 'Dudley', null],
        ['E', 'London E', null],
        ['EC', 'London EC', null],
        ['EH', 'Edinburgh', null],
        ['EN', 'Enfield', null],
        ['EX', 'Exeter', null],
        ['FK', 'Falkirk', null],
        ['FY', 'Blackpool', null],
        ['G', 'Glasgow', null],
        ['GL', 'Gloucester', null],
        ['GU', 'Guildford', null],
        ['GY', 'Guernsey', null],
        ['HA', 'Harrow', null],
        ['HD', 'Huddersfield', null],
        ['HG', 'Harrogate', null],
        ['HP', 'Hemel Hempstead', null],
        ['HR', 'Hereford', null],
        ['HS', 'Outer Hebrides', null],
        ['HU', 'Hull', null],
        ['HX', 'Halifax', null],
        ['IC', 'Channel Islands', null],
        ['IG', 'Ilford', null],
        ['IM', 'Isle of Man', null],
        ['IP', 'Ipswich', null],
        ['IV', 'Inverness', null],
        ['JE', 'Jersey', null],
        ['KA', 'Kilmarnock', null],
        ['KT', 'Kingston upon Thames', null],
        ['KW', 'Kirkwall', null],
        ['KY', 'Kirkcaldy', null],
        ['L', 'Liverpool', null],
        ['LA', 'Lancaster', null],
        ['LD', 'Llandrindod Wells', null],
        ['LE', 'Leicester', null],
        ['LL', 'Llandudno', null],
        ['LN', 'Lincoln', null],
        ['LS', 'Leeds', null],
        ['LU', 'Luton', null],
        ['M', 'Manchester', null],
        ['ME', 'Medway', null],
        ['MK', 'Milton Keynes', null],
        ['ML', 'Motherwell', null],
        ['N', 'London N', null],
        ['NE', 'Newcastle upon Tyne', null],
        ['NG', 'Nottingham', null],
        ['NN', 'Northampton', null],
        ['NP', 'Newport', null],
        ['NR', 'Norwich', null],
        ['NW', 'London NW', null],
        ['OL', 'Oldham', null],
        ['OX', 'Oxford', null],
        ['PA', 'Paisley', null],
        ['PE', 'Peterborough', null],
        ['PH', 'Perth', null],
        ['PL', 'Plymouth', null],
        ['PO', 'Portsmouth', null],
        ['PR', 'Preston', null],
        ['RG', 'Reading', null],
        ['RH', 'Redhill', null],
        ['RM', 'Romford', null],
        ['S', 'Sheffield', null],
        ['SA', 'Swansea', null],
        ['SE', 'London SE', null],
        ['SG', 'Stevenage', null],
        ['SK', 'Stockport', null],
        ['SL', 'Slough', null],
        ['SM', 'Sutton', null],
        ['SN', 'Swindon', null],
        ['SO', 'Southampton', null],
        ['SP', 'Salisbury', null],
        ['SR', 'Sunderland', null],
        ['SS', 'Southend-on-Sea', null],
        ['ST', 'Stoke-on-Trent', null],
        ['SW', 'London SW', null],
        ['SY', 'Shrewsbury', null],
        ['TA', 'Taunton', null],
        ['TD', 'Galashiels', null],
        ['TF', 'Telford', null],
        ['TN', 'Tonbridge', null],
        ['TQ', 'Torquay', null],
        ['TR', 'Truro', null],
        ['TS', 'Cleveland', null],
        ['TW', 'Twickenham', null],
        ['UB', 'Southall', null],
        ['W', 'London W', null],
        ['WA', 'Warrington', null],
        ['WC', 'London WC', null],
        ['WD', 'Watford', null],
        ['WF', 'Wakefield', null],
        ['WN', 'Wigan', null],
        ['WR', 'Worcester', null],
        ['WS', 'Walsall', null],
        ['WV', 'Wolverhampton', null],
        ['YO', 'York', null],
        ['ZE', 'Lerwick', null]
    ]
};
