При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-16. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_16','','988','','','','Митенки короткие-16','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 348704 Повязка на голову д/д. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','126','126','126','348704_povyazka_na_golovu_d_d','','937','','','','348704 Повязка на голову д/д','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-20. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_20','','988','','','','Митенки короткие-20','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К104м Конверт меховой в коляску. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','3538','3538','3538','k104m_konvert_mekhovoy_v_kolyasku','','976','','','','К104м Конверт меховой в коляску','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К27-5 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','206','206','206','k27_5_ugolok_dlya_novorozhdennogo','','981','','','','К27-5 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-7 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_7_prostynka_na_rezinke','','981','','','','К49-7 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342709 Комплект аксессуаров: бусы, браслет, кольцо. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('3','2015-02-17 17:02:03',NULL,NULL,'0','302','302','302','342709_komplekt_aksessuarov_busy_braslet_kolco','','937','','','','342709 Комплект аксессуаров: бусы, браслет, кольцо','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К50-2 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('3','2015-02-17 17:02:03',NULL,NULL,'0','268','268','268','k50_2_prostynka_na_rezinke','','981','','','','К50-2 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-25. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_25','','988','','','','Митенки длинные-25','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К102-2 Конверт прогулочный. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','1870','1870','1870','k102_2_konvert_progulochnyy','','976','','','','К102-2 Конверт прогулочный','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К28-2 Уголок крестильный (шитье). Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','348','348','348','k28_2_ugolok_krestilnyy_shite_','','981','','','','К28-2 Уголок крестильный (шитье)','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура ИГ-9980 Нагрудник салат-4. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('14','2015-02-17 17:02:03',NULL,NULL,'0','45','45','45','ig_9980_nagrudnik_salat_4','','982','','','','ИГ-9980 Нагрудник салат-4','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-18. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_18','','988','','','','Митенки длинные-18','Митенки длинные-1: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 348701 Повязка на голову д/д. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','108','108','108','348701_povyazka_na_golovu_d_d','','937','','','','348701 Повязка на голову д/д','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-13. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_13','','988','','','','Митенки короткие-13','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К27-2 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','206','206','206','k27_2_ugolok_dlya_novorozhdennogo','','981','','','','К27-2 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-4 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_4_prostynka_na_rezinke','','981','','','','К49-4 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342714 Резинка. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','76','76','76','342714_rezinka','','937','','','','342714 Резинка','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-17. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_17','','988','','','','Митенки короткие-17','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К29-1 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','378','378','378','k29_1_ugolok_dlya_novorozhdennogo','','981','','','','К29-1 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-22. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_22','','988','','','','Митенки длинные-22','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342705 Ободок. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','151','151','151','342705_obodok','','937','','','','342705 Ободок','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К104 Конверт прогулочный в коляску бежевый. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','2338','2338','2338','k104_konvert_progulochnyy_v_kolyasku_bezhevyy','','976','','','','К104 Конверт прогулочный в коляску бежевый','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-15. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('3','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_15','','988','','','','Митенки длинные-15','Митенки длинные-1: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 21108-0001 GKC Воротник д/д. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','0','0','0','21108_0001_gkc_vorotnik_d_d','','912','','','','21108-0001 GKC Воротник д/д','21101-0101 GMS Рейтузы д/д: 28/104',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура ИГ-9980 Нагрудник молочный-1. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('13','2015-02-17 17:02:03',NULL,NULL,'0','45','45','45','ig_9980_nagrudnik_molochnyy_1','','982','','','','ИГ-9980 Нагрудник молочный-1','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К50-3 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','268','268','268','k50_3_prostynka_na_rezinke','','981','','','','К50-3 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-1 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_1_prostynka_na_rezinke','','981','','','','К49-1 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-26. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_26','','988','','','','Митенки длинные-26','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342711 Резинки 2шт.. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','63','63','63','342711_rezinki_2sht','','937','','','','342711 Резинки 2шт.','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К28-3 Уголок крестильный (шитье). Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','348','348','348','k28_3_ugolok_krestilnyy_shite_','','981','','','','К28-3 Уголок крестильный (шитье)','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура ИГ-9980 Нагрудник розовый-5. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('15','2015-02-17 17:02:03',NULL,NULL,'0','45','45','45','ig_9980_nagrudnik_rozovyy_5','','982','','','','ИГ-9980 Нагрудник розовый-5','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-19. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_19','','988','','','','Митенки длинные-19','Митенки длинные-1: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 6118-Р Пинетки велюровые собачки розовые. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','384','384','384','6118_r_pinetki_velyurovye_sobachki_rozovye','','968','','','','6118-Р Пинетки велюровые собачки розовые','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-14. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_14','','988','','','','Митенки короткие-14','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К27-3 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','206','206','206','k27_3_ugolok_dlya_novorozhdennogo','','981','','','','К27-3 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342717 Заколки 8 шт.. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','142','142','142','342717_zakolki_8_sht','','937','','','','342717 Заколки 8 шт.','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-5 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_5_prostynka_na_rezinke','','981','','','','К49-5 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342706 Комплект аксессуаров: 2 резинки, ободок. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('4','2015-02-17 17:02:03',NULL,NULL,'0','160','160','160','342706_komplekt_aksessuarov_2_rezinki_obodok','','937','','','','342706 Комплект аксессуаров: 2 резинки, ободок','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-23. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_23','','988','','','','Митенки длинные-23','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К104 Конверт прогулочный в коляску бордовый. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','2338','2338','2338','k104_konvert_progulochnyy_v_kolyasku_bordovyy','','976','','','','К104 Конверт прогулочный в коляску бордовый','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-18. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_18','','988','','','','Митенки короткие-18','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К37 Уголок для новорожденного (сатин, органза). Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','416','416','416','k37_ugolok_dlya_novorozhdennogo_satin_organza_','','981','','','','К37 Уголок для новорожденного (сатин, органза)','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура ИГ-9980 Нагрудник голубой-2. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('13','2015-02-17 17:02:03',NULL,NULL,'0','45','45','45','ig_9980_nagrudnik_goluboy_2','','982','','','','ИГ-9980 Нагрудник голубой-2','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-11. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_11','','988','','','','Митенки короткие-11','Митенки короткие-10: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-16. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_16','','988','','','','Митенки длинные-16','Митенки длинные-1: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К29-2 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','378','378','378','k29_2_ugolok_dlya_novorozhdennogo','','981','','','','К29-2 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342712 Заколки 2шт.. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('4','2015-02-17 17:02:03',NULL,NULL,'0','72','72','72','342712_zakolki_2sht','','937','','','','342712 Заколки 2шт.','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К50-4 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','268','268','268','k50_4_prostynka_na_rezinke','','981','','','','К50-4 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-2 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_2_prostynka_na_rezinke','','981','','','','К49-2 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342702 Резинки 2шт.. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('3','2015-02-17 17:02:03',NULL,NULL,'0','95','95','95','342702_rezinki_2sht','','937','','','','342702 Резинки 2шт.','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 9060-В Пинетки голубые "Морячок" . Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','328','328','328','9060_v_pinetki_golubye_moryachok_','','968','','','','9060-В Пинетки голубые "Морячок" ','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К28-4 Уголок крестильный (шитье). Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','348','348','348','k28_4_ugolok_krestilnyy_shite_','','981','','','','К28-4 Уголок крестильный (шитье)','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-15. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('4','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_15','','988','','','','Митенки короткие-15','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-20. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_20','','988','','','','Митенки длинные-20','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 348703 Повязка на голову д/д. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','90','90','90','348703_povyazka_na_golovu_d_d','','937','','','','348703 Повязка на голову д/д','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура ИГ-9980-6 Нагрудник . Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','45','45','45','ig_9980_6_nagrudnik_','','982','','','','ИГ-9980-6 Нагрудник ','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К116м Конверт-трансформер меховой в коляску. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','3662','3662','3662','k116m_konvert_transformer_mekhovoy_v_kolyasku','','976','','','','К116м Конверт-трансформер меховой в коляску','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К27-4 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','206','206','206','k27_4_ugolok_dlya_novorozhdennogo','','981','','','','К27-4 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-6 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_6_prostynka_na_rezinke','','981','','','','К49-6 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-24. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_24','','988','','','','Митенки длинные-24','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342707 Комплект аксессуаров: 2 резинки, ободок. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('5','2015-02-17 17:02:03',NULL,NULL,'0','158','158','158','342707_komplekt_aksessuarov_2_rezinki_obodok','','937','','','','342707 Комплект аксессуаров: 2 резинки, ободок','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К50-1 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('4','2015-02-17 17:02:03',NULL,NULL,'0','268','268','268','k50_1_prostynka_na_rezinke','','981','','','','К50-1 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 105168 Конверт прогулочный бордовый. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','2200','2200','2200','105168_konvert_progulochnyy_bordovyy','','976','','','','105168 Конверт прогулочный бордовый','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-19. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_19','','988','','','','Митенки короткие-19','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К102-1 Конверт прогулочный. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','1870','1870','1870','k102_1_konvert_progulochnyy','','976','','','','К102-1 Конверт прогулочный','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К28-1 Уголок крестильный (шитье). Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','348','348','348','k28_1_ugolok_krestilnyy_shite_','','981','','','','К28-1 Уголок крестильный (шитье)','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура ИГ-9980 Нагрудник жёлтый-3. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('15','2015-02-17 17:02:03',NULL,NULL,'0','45','45','45','ig_9980_nagrudnik_zheltyy_3','','982','','','','ИГ-9980 Нагрудник жёлтый-3','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки короткие-12. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','270','270','270','mitenki_korotkie_12','','988','','','','Митенки короткие-12','Митенки короткие-1: 21',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-17. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_17','','988','','','','Митенки длинные-17','Митенки длинные-1: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 6115-В Пинетки велюровые слонята голубые. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','384','384','384','6115_v_pinetki_velyurovye_slonyata_golubye','','968','','','','6115-В Пинетки велюровые слонята голубые','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К27-1 Уголок для новорожденного. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','206','206','206','k27_1_ugolok_dlya_novorozhdennogo','','981','','','','К27-1 Уголок для новорожденного','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342713 Резинки 6шт.. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('2','2015-02-17 17:02:03',NULL,NULL,'0','189','189','189','342713_rezinki_6sht','','937','','','','342713 Резинки 6шт.','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К49-3 Простынка на резинке. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','280','280','280','k49_3_prostynka_na_rezinke','','981','','','','К49-3 Простынка на резинке','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура Митенки длинные-21. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','360','360','360','mitenki_dlinnye_21','','988','','','','Митенки длинные-21','Митенки длинные-2: 26',NULL,NULL,'1','0',NULL,NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 342703 Ободок. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('5','2015-02-17 17:02:03',NULL,NULL,'0','95','95','95','342703_obodok','','937','','','','342703 Ободок','',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура 105168 Конверт прогулочный зеленый. Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('0','2015-02-17 17:02:03',NULL,NULL,'0','2200','2200','2200','105168_konvert_progulochnyy_zelenyy','','976','','','','105168 Конверт прогулочный зеленый','28-1383-1 Конверт: 20/50-56',NULL,NULL,'1','0','4',NULL)
При выполнении создания объекта (cms1c.ru) Номенклатура К28-5 Уголок крестильный (шитье). Ошибка: Column 'sku_count' cannot be null
Текст запроса : INSERT INTO `shop_product` (`count`,`create_datetime`,`currency`,`ext`,`id`,`max_price`,`min_price`,`price`,`url`,`meta_title`,`category_id`,`meta_keywords`,`summary`,`meta_description`,`name`,`description`,`image_id`,`sku_id`,`status`,`sku_type`,`type_id`,`sku_count`) VALUES
('1','2015-02-17 17:02:03',NULL,NULL,'0','348','348','348','k28_5_ugolok_krestilnyy_shite_','','981','','','','К28-5 Уголок крестильный (шитье)','',NULL,NULL,'1','0','4',NULL)
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//19/43/4319/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//29/30/13029/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
Невозможно найти на ФТП файл /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292/images, Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
Невозможно создать файл на FTP /www/pchelkinazabava.ru/wa-data/protected/shop/products//92/92/19292/images. Причина: {Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка работы с Интернет:  ftp://89.108.79.244:21Quote command returned error
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (НайтиФайлы): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
{Обработка.CMS1C_ОбработкаОбмена.МодульОбъекта}: Ошибка при вызове метода контекста (Записать): Ошибка аутентификации при доступе к ресурсу:  ftp://89.108.79.244:21Access denied to remote resource
