DROP TABLE IF EXISTS `checklists_list`;
CREATE TABLE IF NOT EXISTS `checklists_list` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`color_class` VARCHAR(32) NOT NULL DEFAULT 'c-white',
	`icon` VARCHAR(255) NOT NULL DEFAULT 'notebook',
	`count` INT NOT NULL DEFAULT '0',
	`sort` INT NOT NULL DEFAULT '0',
	INDEX (`sort`)
) ENGINE = MYISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `checklists_list_items`;
CREATE TABLE IF NOT EXISTS `checklists_list_items` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`list_id` INT UNSIGNED NOT NULL ,
	`name` VARCHAR( 255 ) NOT NULL ,
	`done` DATETIME NULL DEFAULT NULL ,
	`contact_id` BIGINT UNSIGNED NULL DEFAULT NULL ,
	`sort` INT NOT NULL DEFAULT  '0',
	INDEX (`list_id`),
	INDEX (`sort`)
) ENGINE = MYISAM DEFAULT CHARSET=utf8;
