<?php

return array(
    'BD' => array(
        'currency' => 'BDT',
        'dimensional_unit' => 'CM',
        'name' => 'Bangladesh',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BE' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Belgium',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'BF' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => 'Burkina Faso',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BG' => array(
        'currency' => 'BGN',
        'dimensional_unit' => 'CM',
        'name' => 'Bulgaria',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BA' => array(
        'currency' => 'BAM',
        'dimensional_unit' => 'CM',
        'name' => 'Bosnia and Herzegovina',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BB' => array(
        'currency' => 'BBD',
        'dimensional_unit' => 'IN',
        'name' => 'Barbados',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'BM' => array(
        'currency' => 'BMD',
        'dimensional_unit' => 'IN',
        'name' => 'Bermuda',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'BN' => array(
        'currency' => 'BND',
        'dimensional_unit' => 'CM',
        'name' => 'Brunei',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'BO' => array(
        'currency' => 'BOB',
        'dimensional_unit' => 'CM',
        'name' => 'Bolivia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BH' => array(
        'currency' => 'BHD',
        'dimensional_unit' => 'CM',
        'name' => 'Bahrain',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BI' => array(
        'currency' => 'BIF',
        'dimensional_unit' => 'CM',
        'name' => 'Burundi',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BJ' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => 'Benin',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BT' => array(
        'currency' => 'BTN',
        'dimensional_unit' => 'CM',
        'name' => 'Bhutan',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'JM' => array(
        'currency' => 'JMD',
        'dimensional_unit' => 'CM',
        'name' => 'Jamaica',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BW' => array(
        'currency' => 'BWP',
        'dimensional_unit' => 'CM',
        'name' => 'Botswana',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'WS' => array(
        'currency' => 'WST',
        'dimensional_unit' => 'CM',
        'name' => 'Samoa',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BR' => array(
        'currency' => 'BRL',
        'dimensional_unit' => 'CM',
        'name' => 'Brazil',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BS' => array(
        'currency' => 'BSD',
        'dimensional_unit' => 'IN',
        'name' => 'Bahamas',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'JE' => array(
        'currency' => 'GBP',
        'dimensional_unit' => 'CM',
        'name' => 'Jersey',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'BY' => array(
        'currency' => 'BYR',
        'dimensional_unit' => 'CM',
        'name' => 'Belarus',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'BZ' => array(
        'currency' => 'BZD',
        'dimensional_unit' => 'CM',
        'name' => 'Belize',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'RU' => array(
        'currency' => 'RUB',
        'dimensional_unit' => 'CM',
        'name' => 'Russian Federation, The',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'RW' => array(
        'currency' => 'RWF',
        'dimensional_unit' => 'CM',
        'name' => 'Rwanda',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'RS' => array(
        'currency' => 'RSD',
        'dimensional_unit' => 'CM',
        'name' => 'Serbia, Republic of        ',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TL' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'CM',
        'name' => 'East Timor',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'RE' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Reunion, Island Of',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'TJ' => array(
        'currency' => 'TJS',
        'dimensional_unit' => 'CM',
        'name' => 'Tajikistan',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'RO' => array(
        'currency' => 'RON',
        'dimensional_unit' => 'CM',
        'name' => 'Romania',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'GW' => array(
        'currency' => 'GWP',
        'dimensional_unit' => 'CM',
        'name' => 'Guinea-Bissau',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GU' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Guam',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'GT' => array(
        'currency' => 'GTQ',
        'dimensional_unit' => 'CM',
        'name' => 'Guatemala',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GR' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Greece',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'GQ' => array(
        'currency' => 'XAF',
        'dimensional_unit' => 'CM',
        'name' => 'Guinea-Equatorial',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GP' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Guadeloupe',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'JP' => array(
        'currency' => 'JPY',
        'dimensional_unit' => 'CM',
        'name' => 'Japan',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'GY' => array(
        'currency' => 'GYD',
        'dimensional_unit' => 'IN',
        'name' => 'Guyana (British)',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'GG' => array(
        'currency' => 'GBP',
        'dimensional_unit' => 'CM',
        'name' => 'Guernsey',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GF' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'French Guyana',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GE' => array(
        'currency' => 'GEL',
        'dimensional_unit' => 'CM',
        'name' => 'Georgia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GD' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'Grenada',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'GB' => array(
        'currency' => 'GBP',
        'dimensional_unit' => 'CM',
        'name' => 'United Kingdom',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'GA' => array(
        'currency' => 'XAF',
        'dimensional_unit' => 'CM',
        'name' => 'Gabon',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SV' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'CM',
        'name' => 'El Salvador',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GN' => array(
        'currency' => 'GNF',
        'dimensional_unit' => 'CM',
        'name' => 'Guinea Republic',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GM' => array(
        'currency' => 'GMD',
        'dimensional_unit' => 'CM',
        'name' => 'Gambia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GL' => array(
        'currency' => 'DKK',
        'dimensional_unit' => 'CM',
        'name' => 'Greenland',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GI' => array(
        'currency' => 'GIP',
        'dimensional_unit' => 'CM',
        'name' => 'Gibraltar',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'GH' => array(
        'currency' => 'GHS',
        'dimensional_unit' => 'CM',
        'name' => 'Ghana',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'OM' => array(
        'currency' => 'OMR',
        'dimensional_unit' => 'CM',
        'name' => 'Oman',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TN' => array(
        'currency' => 'TND',
        'dimensional_unit' => 'CM',
        'name' => 'Tunisia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'JO' => array(
        'currency' => 'JOD',
        'dimensional_unit' => 'CM',
        'name' => 'Jordan',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'HR' => array(
        'currency' => 'HRK',
        'dimensional_unit' => 'CM',
        'name' => 'Croatia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'HT' => array(
        'currency' => 'HTG',
        'dimensional_unit' => 'IN',
        'name' => 'Haiti',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'HU' => array(
        'currency' => 'HUF',
        'dimensional_unit' => 'CM',
        'name' => 'Hungary',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'HK' => array(
        'currency' => 'HKD',
        'dimensional_unit' => 'CM',
        'name' => 'Hong Kong',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'HN' => array(
        'currency' => 'HNL',
        'dimensional_unit' => 'CM',
        'name' => 'Honduras',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'XN' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'Nevis',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'VE' => array(
        'currency' => 'VEF',
        'dimensional_unit' => 'CM',
        'name' => 'Venezuela',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PR' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Puerto Rico',
        'weight_unit' => 'LB',
        'use_division' => true,
    ),
    'PW' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'CM',
        'name' => 'Palau                         ',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PT' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Portugal',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PY' => array(
        'currency' => 'PYG',
        'dimensional_unit' => 'CM',
        'name' => 'Paraguay',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'IQ' => array(
        'currency' => 'IQD',
        'dimensional_unit' => 'CM',
        'name' => 'Iraq                          ',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PA' => array(
        'currency' => 'PAB',
        'dimensional_unit' => 'CM',
        'name' => 'Panama',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PF' => array(
        'currency' => 'XPF',
        'dimensional_unit' => 'CM',
        'name' => 'Tahiti',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PG' => array(
        'currency' => 'PGK',
        'dimensional_unit' => 'CM',
        'name' => 'Papua New Guinea',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PE' => array(
        'currency' => 'PEN',
        'dimensional_unit' => 'CM',
        'name' => 'Peru',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PK' => array(
        'currency' => 'PKR',
        'dimensional_unit' => 'CM',
        'name' => 'Pakistan',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'PH' => array(
        'currency' => 'PHP',
        'dimensional_unit' => 'CM',
        'name' => 'Philippines, The',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'PL' => array(
        'currency' => 'PLN',
        'dimensional_unit' => 'CM',
        'name' => 'Poland',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SN' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => 'Senegal',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ZM' => array(
        'currency' => 'ZMK',
        'dimensional_unit' => 'CM',
        'name' => 'Zambia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'EE' => array(
        'currency' => 'EEK',
        'dimensional_unit' => 'CM',
        'name' => 'Estonia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'EG' => array(
        'currency' => 'EGP',
        'dimensional_unit' => 'CM',
        'name' => 'Egypt',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ZA' => array(
        'currency' => 'ZAR',
        'dimensional_unit' => 'CM',
        'name' => 'South Africa',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'EC' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'CM',
        'name' => 'Ecuador',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'IT' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Italy',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'VN' => array(
        'currency' => 'VND',
        'dimensional_unit' => 'CM',
        'name' => 'Vietnam',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SB' => array(
        'currency' => 'SBD',
        'dimensional_unit' => 'CM',
        'name' => 'Solomon Islands',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ET' => array(
        'currency' => 'ETB',
        'dimensional_unit' => 'CM',
        'name' => 'Ethiopia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SO' => array(
        'currency' => 'SOS',
        'dimensional_unit' => 'CM',
        'name' => 'Somalia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ZW' => array(
        'currency' => 'ZWD',
        'dimensional_unit' => 'CM',
        'name' => 'Zimbabwe',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SA' => array(
        'currency' => 'SAR',
        'dimensional_unit' => 'CM',
        'name' => 'Saudi Arabia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ES' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Spain',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ER' => array(
        'currency' => 'ERN',
        'dimensional_unit' => 'CM',
        'name' => 'Eritrea',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ME' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Montenegro, Republic of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MD' => array(
        'currency' => 'MDL',
        'dimensional_unit' => 'CM',
        'name' => 'Moldova, Republic Of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MG' => array(
        'currency' => 'MGA',
        'dimensional_unit' => 'CM',
        'name' => 'Madagascar',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MA' => array(
        'currency' => 'MAD',
        'dimensional_unit' => 'CM',
        'name' => 'Morocco',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MC' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Monaco',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'UZ' => array(
        'currency' => 'UZS',
        'dimensional_unit' => 'CM',
        'name' => 'Uzbekistan',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'MM' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'CM',
        'name' => 'Myanmar',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ML' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => 'Mali',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MO' => array(
        'currency' => 'MOP',
        'dimensional_unit' => 'CM',
        'name' => 'Macau',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MN' => array(
        'currency' => 'MNT',
        'dimensional_unit' => 'CM',
        'name' => 'Mongolia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MH' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Marshall Islands',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'MK' => array(
        'currency' => 'MKD',
        'dimensional_unit' => 'CM',
        'name' => 'Macedonia, Rep. of (FYROM)',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MU' => array(
        'currency' => 'MUR',
        'dimensional_unit' => 'CM',
        'name' => 'Mauritius',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MT' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Malta',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MW' => array(
        'currency' => 'MWK',
        'dimensional_unit' => 'CM',
        'name' => 'Malawi',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MV' => array(
        'currency' => 'MVR',
        'dimensional_unit' => 'CM',
        'name' => 'Maldives',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MQ' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Martinique',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MP' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Saipan',
        'weight_unit' => 'LB',
        'use_division' => true,
    ),
    'MS' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'Montserrat',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'MR' => array(
        'currency' => 'MRO',
        'dimensional_unit' => 'CM',
        'name' => 'Mauritania',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'UG' => array(
        'currency' => 'UGX',
        'dimensional_unit' => 'CM',
        'name' => 'Uganda',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MY' => array(
        'currency' => 'MYR',
        'dimensional_unit' => 'CM',
        'name' => 'Malaysia',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'MX' => array(
        'currency' => 'MXN',
        'dimensional_unit' => 'CM',
        'name' => 'Mexico',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'IL' => array(
        'currency' => 'ILS',
        'dimensional_unit' => 'CM',
        'name' => 'Israel',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'FR' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'France',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'XS' => array(
        'currency' => 'SIS',
        'dimensional_unit' => 'CM',
        'name' => 'Somaliland, Rep of (North Somalia)',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'FI' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Finland',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'FJ' => array(
        'currency' => 'FJD',
        'dimensional_unit' => 'CM',
        'name' => 'Fiji',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'FK' => array(
        'currency' => 'FKP',
        'dimensional_unit' => 'CM',
        'name' => 'Falkland Islands',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'FM' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'MICRONESIA, FEDERATED STATES OF    ',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'FO' => array(
        'currency' => 'DKK',
        'dimensional_unit' => 'CM',
        'name' => 'Faroe Islands',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NI' => array(
        'currency' => 'NIO',
        'dimensional_unit' => 'CM',
        'name' => 'Nicaragua',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NL' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Netherlands, The',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'NO' => array(
        'currency' => 'NOK',
        'dimensional_unit' => 'CM',
        'name' => 'Norway',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NA' => array(
        'currency' => 'ZAR',
        'dimensional_unit' => 'CM',
        'name' => 'Namibia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'VU' => array(
        'currency' => 'VUV',
        'dimensional_unit' => 'CM',
        'name' => 'Vanuatu',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NC' => array(
        'currency' => 'XPF',
        'dimensional_unit' => 'CM',
        'name' => 'New Caledonia',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'NE' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => 'Niger',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NG' => array(
        'currency' => 'NGN',
        'dimensional_unit' => 'CM',
        'name' => 'Nigeria',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NZ' => array(
        'currency' => 'NZD',
        'dimensional_unit' => 'CM',
        'name' => 'New Zealand',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'NP' => array(
        'currency' => 'NPR',
        'dimensional_unit' => 'CM',
        'name' => 'Nepal',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NR' => array(
        'currency' => 'AUD',
        'dimensional_unit' => 'CM',
        'name' => 'Nauru, Republic Of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'NU' => array(
        'currency' => 'NZD',
        'dimensional_unit' => 'CM',
        'name' => 'Niue',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CK' => array(
        'currency' => 'NZD',
        'dimensional_unit' => 'CM',
        'name' => 'Cook Islands',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CI' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => "Cote d'Ivoire",
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CH' => array(
        'currency' => 'CHF',
        'dimensional_unit' => 'CM',
        'name' => 'Switzerland',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'CO' => array(
        'currency' => 'COP',
        'dimensional_unit' => 'CM',
        'name' => 'Colombia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CN' => array(
        'currency' => 'CNY',
        'dimensional_unit' => 'CM',
        'name' => "China, People's Republic",
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'CM' => array(
        'currency' => 'XAF',
        'dimensional_unit' => 'CM',
        'name' => 'Cameroon',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CL' => array(
        'currency' => 'CLP',
        'dimensional_unit' => 'CM',
        'name' => 'Chile',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'XB' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'IN',
        'name' => 'Bonaire',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'XC' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'IN',
        'name' => 'Curacao',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'CA' => array(
        'currency' => 'CAD',
        'dimensional_unit' => 'IN',
        'name' => 'Canada',
        'weight_unit' => 'LB',
        'use_division' => true,
    ),
    'CG' => array(
        'currency' => 'XAF',
        'dimensional_unit' => 'CM',
        'name' => 'Congo',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CF' => array(
        'currency' => 'XAF',
        'dimensional_unit' => 'CM',
        'name' => 'Central African Republic',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CD' => array(
        'currency' => 'CDF',
        'dimensional_unit' => 'CM',
        'name' => 'Congo, The Democratic Republic of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CZ' => array(
        'currency' => 'CZK',
        'dimensional_unit' => 'CM',
        'name' => 'Czech Republic, The',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'CY' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Cyprus',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'XY' => array(
        'currency' => 'ANG',
        'dimensional_unit' => 'IN',
        'name' => 'St. Barthelemy',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'CR' => array(
        'currency' => 'CRC',
        'dimensional_unit' => 'CM',
        'name' => 'Costa Rica',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CV' => array(
        'currency' => 'CVE',
        'dimensional_unit' => 'CM',
        'name' => 'Cape Verde',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'CU' => array(
        'currency' => 'CUP',
        'dimensional_unit' => 'CM',
        'name' => 'Cuba',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SZ' => array(
        'currency' => 'SZL',
        'dimensional_unit' => 'CM',
        'name' => 'Swaziland',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SY' => array(
        'currency' => 'SYP',
        'dimensional_unit' => 'CM',
        'name' => 'Syria',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KG' => array(
        'currency' => 'KGS',
        'dimensional_unit' => 'CM',
        'name' => 'Kyrgyzstan',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'KE' => array(
        'currency' => 'KES',
        'dimensional_unit' => 'CM',
        'name' => 'Kenya',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SS' => array(
        'currency' => 'SSP',
        'dimensional_unit' => 'CM',
        'name' => 'SOUTH SUDAN',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SR' => array(
        'currency' => 'SRD',
        'dimensional_unit' => 'CM',
        'name' => 'Suriname',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KI' => array(
        'currency' => 'AUD',
        'dimensional_unit' => 'CM',
        'name' => 'Kiribati',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KH' => array(
        'currency' => 'KHR',
        'dimensional_unit' => 'CM',
        'name' => 'Cambodia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KN' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'St. Kitts',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'KM' => array(
        'currency' => 'KMF',
        'dimensional_unit' => 'CM',
        'name' => 'Comoros',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ST' => array(
        'currency' => 'STD',
        'dimensional_unit' => 'CM',
        'name' => 'Sao Tome and Principe',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SK' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Slovakia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KR' => array(
        'currency' => 'KRW',
        'dimensional_unit' => 'CM',
        'name' => 'Korea, Republic Of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SI' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Slovenia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KP' => array(
        'currency' => 'KPW',
        'dimensional_unit' => 'CM',
        'name' => 'Korea, The D.P.R of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KW' => array(
        'currency' => 'KWD',
        'dimensional_unit' => 'CM',
        'name' => 'Kuwait',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KV' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Kosovo                          ',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SM' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'San Marino                       ',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SL' => array(
        'currency' => 'SLL',
        'dimensional_unit' => 'CM',
        'name' => 'Sierra Leone',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SC' => array(
        'currency' => 'SCR',
        'dimensional_unit' => 'CM',
        'name' => 'Seychelles',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'KZ' => array(
        'currency' => 'KZT',
        'dimensional_unit' => 'CM',
        'name' => 'Kazakhstan',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'KY' => array(
        'currency' => 'KYD',
        'dimensional_unit' => 'IN',
        'name' => 'Cayman Islands',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'SG' => array(
        'currency' => 'SGD',
        'dimensional_unit' => 'CM',
        'name' => 'Singapore',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SE' => array(
        'currency' => 'SEK',
        'dimensional_unit' => 'CM',
        'name' => 'Sweden',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'SD' => array(
        'currency' => 'SDG',
        'dimensional_unit' => 'CM',
        'name' => 'Sudan',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'DO' => array(
        'currency' => 'DOP',
        'dimensional_unit' => 'IN',
        'name' => 'Dominican Rep.',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'DM' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'CM',
        'name' => 'Dominica',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'DJ' => array(
        'currency' => 'DJF',
        'dimensional_unit' => 'CM',
        'name' => 'Djibouti',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'DK' => array(
        'currency' => 'DKK',
        'dimensional_unit' => 'CM',
        'name' => 'Denmark',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'VG' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Virgin Islands (British)',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'DE' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Germany',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'YE' => array(
        'currency' => 'YER',
        'dimensional_unit' => 'CM',
        'name' => 'Yemen, Republic of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'DZ' => array(
        'currency' => 'DZD',
        'dimensional_unit' => 'CM',
        'name' => 'Algeria',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'US' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'United States Of America',
        'weight_unit' => 'LB',
        'use_division' => true,
    ),
    'UY' => array(
        'currency' => 'UYU',
        'dimensional_unit' => 'CM',
        'name' => 'Uruguay',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'YT' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Mayotte',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LB' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'CM',
        'name' => 'Lebanon',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LC' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'St. Lucia',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'LA' => array(
        'currency' => 'LAK',
        'dimensional_unit' => 'CM',
        'name' => "Lao People's Democratic Republic",
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TV' => array(
        'currency' => 'AUD',
        'dimensional_unit' => 'CM',
        'name' => 'Tuvalu',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TW' => array(
        'currency' => 'TWD',
        'dimensional_unit' => 'CM',
        'name' => 'Taiwan',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'TT' => array(
        'currency' => 'TTD',
        'dimensional_unit' => 'IN',
        'name' => 'Trinidad and Tobago',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'XM' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'IN',
        'name' => 'St. Maarten',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'TR' => array(
        'currency' => 'TRY',
        'dimensional_unit' => 'CM',
        'name' => 'Turkey',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'LK' => array(
        'currency' => 'LKR',
        'dimensional_unit' => 'CM',
        'name' => 'Sri Lanka',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LI' => array(
        'currency' => 'CHF',
        'dimensional_unit' => 'CM',
        'name' => 'Liechtenstein',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LV' => array(
        'currency' => 'LVL',
        'dimensional_unit' => 'CM',
        'name' => 'Latvia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TO' => array(
        'currency' => 'TOP',
        'dimensional_unit' => 'CM',
        'name' => 'Tonga',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LT' => array(
        'currency' => 'LTL',
        'dimensional_unit' => 'CM',
        'name' => 'Lithuania',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LU' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Luxembourg',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LR' => array(
        'currency' => 'LRD',
        'dimensional_unit' => 'CM',
        'name' => 'Liberia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'LS' => array(
        'currency' => 'LSL',
        'dimensional_unit' => 'CM',
        'name' => 'Lesotho',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TH' => array(
        'currency' => 'THB',
        'dimensional_unit' => 'CM',
        'name' => 'Thailand',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TG' => array(
        'currency' => 'XOF',
        'dimensional_unit' => 'CM',
        'name' => 'Togo',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TD' => array(
        'currency' => 'XAF',
        'dimensional_unit' => 'CM',
        'name' => 'Chad',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'TC' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Turks and Caicos Islands',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'LY' => array(
        'currency' => 'LYD',
        'dimensional_unit' => 'CM',
        'name' => 'Libya',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'VC' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'St. Vincent',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'AE' => array(
        'currency' => 'AED',
        'dimensional_unit' => 'CM',
        'name' => 'United Arab Emirates',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AD' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Andorra',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AG' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'Antigua',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'AF' => array(
        'currency' => 'AFN',
        'dimensional_unit' => 'CM',
        'name' => 'Afghanistan',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AI' => array(
        'currency' => 'XCD',
        'dimensional_unit' => 'IN',
        'name' => 'Anguilla',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'VI' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'Virgin Islands (US)',
        'weight_unit' => 'LB',
        'use_division' => true,
    ),
    'IS' => array(
        'currency' => 'ISK',
        'dimensional_unit' => 'CM',
        'name' => 'Iceland',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'IR' => array(
        'currency' => 'IRR',
        'dimensional_unit' => 'CM',
        'name' => 'Iran (Islamic Republic of)',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AM' => array(
        'currency' => 'AMD',
        'dimensional_unit' => 'CM',
        'name' => 'Armenia',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'AL' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Albania',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AO' => array(
        'currency' => 'AOA',
        'dimensional_unit' => 'CM',
        'name' => 'Angola',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AN' => array(
        'currency' => 'ANG',
        'dimensional_unit' => 'CM',
        'name' => 'Netherlands Antilles',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AS' => array(
        'currency' => 'USD',
        'dimensional_unit' => 'IN',
        'name' => 'American Samoa',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'AR' => array(
        'currency' => 'ARS',
        'dimensional_unit' => 'CM',
        'name' => 'Argentina',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AU' => array(
        'currency' => 'AUD',
        'dimensional_unit' => 'CM',
        'name' => 'Australia',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'AT' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Austria',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AW' => array(
        'currency' => 'AWG',
        'dimensional_unit' => 'IN',
        'name' => 'Aruba',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'IN' => array(
        'currency' => 'INR',
        'dimensional_unit' => 'CM',
        'name' => 'India',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'TZ' => array(
        'currency' => 'TZS',
        'dimensional_unit' => 'CM',
        'name' => 'Tanzania',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'IC' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Canary Islands, The',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'AZ' => array(
        'currency' => 'AZM',
        'dimensional_unit' => 'CM',
        'name' => 'Azerbaijan',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'IE' => array(
        'currency' => 'EUR',
        'dimensional_unit' => 'CM',
        'name' => 'Ireland, Republic Of',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'ID' => array(
        'currency' => 'IDR',
        'dimensional_unit' => 'CM',
        'name' => 'Indonesia',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'XE' => array(
        'currency' => 'ANG',
        'dimensional_unit' => 'IN',
        'name' => 'St. Eustatius',
        'weight_unit' => 'LB',
        'use_division' => false,
    ),
    'UA' => array(
        'currency' => 'UAH',
        'dimensional_unit' => 'CM',
        'name' => 'Ukraine',
        'weight_unit' => 'KG',
        'use_division' => true,
    ),
    'QA' => array(
        'currency' => 'QAR',
        'dimensional_unit' => 'CM',
        'name' => 'Qatar',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
    'MZ' => array(
        'currency' => 'MZN',
        'dimensional_unit' => 'CM',
        'name' => 'Mozambique',
        'weight_unit' => 'KG',
        'use_division' => false,
    ),
);