INSERT IGNORE INTO `wa_country` (`name`, `iso3letter`, `iso2letter`, `isonumeric`, `fav_sort`) VALUES
('Afghanistan', 'afg', 'af', '004', NULL),
('Åland Islands', 'ala', 'ax', '248', NULL),
('Albania', 'alb', 'al', '008', NULL),
('Algeria', 'dza', 'dz', '012', NULL),
('American Samoa', 'asm', 'as', '016', NULL),
('Andorra', 'and', 'ad', '020', NULL),
('Angola', 'ago', 'ao', '024', NULL),
('Anguilla', 'aia', 'ai', '660', NULL),
('Antigua and Barbuda', 'atg', 'ag', '028', NULL),
('Argentina', 'arg', 'ar', '032', NULL),
('Armenia', 'arm', 'am', '051', NULL),
('Aruba', 'abw', 'aw', '533', NULL),
('Australia', 'aus', 'au', '036', NULL),
('Austria', 'aut', 'at', '040', NULL),
('Azerbaijan', 'aze', 'az', '031', NULL),
('Bahamas', 'bhs', 'bs', '044', NULL),
('Bahrain', 'bhr', 'bh', '048', NULL),
('Bangladesh', 'bgd', 'bd', '050', NULL),
('Barbados', 'brb', 'bb', '052', NULL),
('Belarus', 'blr', 'by', '112', NULL),
('Belgium', 'bel', 'be', '056', NULL),
('Belize', 'blz', 'bz', '084', NULL),
('Benin', 'ben', 'bj', '204', NULL),
('Bermuda', 'bmu', 'bm', '060', NULL),
('Bhutan', 'btn', 'bt', '064', NULL),
('Bolivia, Plurinational State of', 'bol', 'bo', '068', NULL),
('Bosnia and Herzegovina', 'bih', 'ba', '070', NULL),
('Botswana', 'bwa', 'bw', '072', NULL),
('Bouvet Island', 'bvt', 'bv', '074', NULL),
('Brazil', 'bra', 'br', '076', NULL),
('British Indian Ocean Territory', 'iot', 'io', '086', NULL),
('Brunei Darussalam', 'brn', 'bn', '096', NULL),
('Bulgaria', 'bgr', 'bg', '100', NULL),
('Burkina Faso', 'bfa', 'bf', '854', NULL),
('Burundi', 'bdi', 'bi', '108', NULL),
('Côte d''Ivoire', 'civ', 'ci', '384', NULL),
('Cambodia', 'khm', 'kh', '116', NULL),
('Cameroon', 'cmr', 'cm', '120', NULL),
('Canada', 'can', 'ca', '124', NULL),
('Cape Verde', 'cpv', 'cv', '132', NULL),
('Cayman Islands', 'cym', 'ky', '136', NULL),
('Central African Republic', 'caf', 'cf', '140', NULL),
('Chad', 'tcd', 'td', '148', NULL),
('Chile', 'chl', 'cl', '152', NULL),
('China', 'chn', 'cn', '156', NULL),
('Christmas Island', 'cxr', 'cx', '162', NULL),
('Cocos (Keeling) Islands', 'cck', 'cc', '166', NULL),
('Colombia', 'col', 'co', '170', NULL),
('Comoros', 'com', 'km', '174', NULL),
('Congo', 'cog', 'cg', '178', NULL),
('Congo, the Democratic Republic of the', 'cod', 'cd', '180', NULL),
('Cook Islands', 'cok', 'ck', '184', NULL),
('Costa Rica', 'cri', 'cr', '188', NULL),
('Croatia', 'hrv', 'hr', '191', NULL),
('Cuba', 'cub', 'cu', '192', NULL),
('Cyprus', 'cyp', 'cy', '196', NULL),
('Czech Republic', 'cze', 'cz', '203', NULL),
('Denmark', 'dnk', 'dk', '208', NULL),
('Djibouti', 'dji', 'dj', '262', NULL),
('Dominica', 'dma', 'dm', '212', NULL),
('Dominican Republic', 'dom', 'do', '214', NULL),
('Ecuador', 'ecu', 'ec', '218', NULL),
('Egypt', 'egy', 'eg', '818', NULL),
('El Salvador', 'slv', 'sv', '222', NULL),
('Equatorial Guinea', 'gnq', 'gq', '226', NULL),
('Eritrea', 'eri', 'er', '232', NULL),
('Estonia', 'est', 'ee', '233', NULL),
('Ethiopia', 'eth', 'et', '231', NULL),
('Falkland Islands (Malvinas)', 'flk', 'fk', '238', NULL),
('Faroe Islands', 'fro', 'fo', '234', NULL),
('Fiji', 'fji', 'fj', '242', NULL),
('Finland', 'fin', 'fi', '246', NULL),
('France', 'fra', 'fr', '250', NULL),
('French Guiana', 'guf', 'gf', '254', NULL),
('French Polynesia', 'pyf', 'pf', '258', NULL),
('French Southern Territories', 'atf', 'tf', '260', NULL),
('Gabon', 'gab', 'ga', '266', NULL),
('Gambia', 'gmb', 'gm', '270', NULL),
('Georgia', 'geo', 'ge', '268', NULL),
('Germany', 'deu', 'de', '276', NULL),
('Ghana', 'gha', 'gh', '288', NULL),
('Gibraltar', 'gib', 'gi', '292', NULL),
('Greece', 'grc', 'gr', '300', NULL),
('Greenland', 'grl', 'gl', '304', NULL),
('Grenada', 'grd', 'gd', '308', NULL),
('Guadeloupe', 'glp', 'gp', '312', NULL),
('Guam', 'gum', 'gu', '316', NULL),
('Guatemala', 'gtm', 'gt', '320', NULL),
('Guinea', 'gin', 'gn', '324', NULL),
('Guinea-Bissau', 'gnb', 'gw', '624', NULL),
('Guyana', 'guy', 'gy', '328', NULL),
('Haiti', 'hti', 'ht', '332', NULL),
('Heard Island and McDonald Islands', 'hmd', 'hm', '334', NULL),
('Holy See (Vatican City State)', 'vat', 'va', '336', NULL),
('Honduras', 'hnd', 'hn', '340', NULL),
('Hong Kong', 'hkg', 'hk', '344', NULL),
('Hungary', 'hun', 'hu', '348', NULL),
('Iceland', 'isl', 'is', '352', NULL),
('India', 'ind', 'in', '356', NULL),
('Indonesia', 'idn', 'id', '360', NULL),
('Iran, Islamic Republic of', 'irn', 'ir', '364', NULL),
('Iraq', 'irq', 'iq', '368', NULL),
('Ireland', 'irl', 'ie', '372', NULL),
('Israel', 'isr', 'il', '376', NULL),
('Italy', 'ita', 'it', '380', NULL),
('Jamaica', 'jam', 'jm', '388', NULL),
('Japan', 'jpn', 'jp', '392', NULL),
('Jordan', 'jor', 'jo', '400', NULL),
('Kazakhstan', 'kaz', 'kz', '398', NULL),
('Kenya', 'ken', 'ke', '404', NULL),
('Kiribati', 'kir', 'ki', '296', NULL),
('Korea, Democratic People''s Republic of', 'prk', 'kp', '408', NULL),
('Korea, Republic of', 'kor', 'kr', '410', NULL),
('Kuwait', 'kwt', 'kw', '414', NULL),
('Kyrgyzstan', 'kgz', 'kg', '417', NULL),
('Lao People''s Democratic Republic', 'lao', 'la', '418', NULL),
('Latvia', 'lva', 'lv', '428', NULL),
('Lebanon', 'lbn', 'lb', '422', NULL),
('Lesotho', 'lso', 'ls', '426', NULL),
('Liberia', 'lbr', 'lr', '430', NULL),
('Libyan Arab Jamahiriya', 'lby', 'ly', '434', NULL),
('Liechtenstein', 'lie', 'li', '438', NULL),
('Lithuania', 'ltu', 'lt', '440', NULL),
('Luxembourg', 'lux', 'lu', '442', NULL),
('Macao', 'mac', 'mo', '446', NULL),
('Macedonia, the former Yugoslav Republic of', 'mkd', 'mk', '807', NULL),
('Madagascar', 'mdg', 'mg', '450', NULL),
('Malawi', 'mwi', 'mw', '454', NULL),
('Malaysia', 'mys', 'my', '458', NULL),
('Maldives', 'mdv', 'mv', '462', NULL),
('Mali', 'mli', 'ml', '466', NULL),
('Malta', 'mlt', 'mt', '470', NULL),
('Marshall Islands', 'mhl', 'mh', '584', NULL),
('Martinique', 'mtq', 'mq', '474', NULL),
('Mauritania', 'mrt', 'mr', '478', NULL),
('Mauritius', 'mus', 'mu', '480', NULL),
('Mayotte', 'myt', 'yt', '175', NULL),
('Mexico', 'mex', 'mx', '484', NULL),
('Micronesia, Federated States of', 'fsm', 'fm', '583', NULL),
('Moldova, Republic of', 'mda', 'md', '498', NULL),
('Monaco', 'mco', 'mc', '492', NULL),
('Mongolia', 'mng', 'mn', '496', NULL),
('Montenegro', 'mne', 'me', '499', NULL),
('Montserrat', 'msr', 'ms', '500', NULL),
('Morocco', 'mar', 'ma', '504', NULL),
('Mozambique', 'moz', 'mz', '508', NULL),
('Myanmar', 'mmr', 'mm', '104', NULL),
('Namibia', 'nam', 'na', '516', NULL),
('Nauru', 'nru', 'nr', '520', NULL),
('Nepal', 'npl', 'np', '524', NULL),
('Netherlands', 'nld', 'nl', '528', NULL),
('Netherlands Antilles', 'ant', 'an', '530', NULL),
('New Caledonia', 'ncl', 'nc', '540', NULL),
('New Zealand', 'nzl', 'nz', '554', NULL),
('Nicaragua', 'nic', 'ni', '558', NULL),
('Niger', 'ner', 'ne', '562', NULL),
('Nigeria', 'nga', 'ng', '566', NULL),
('Niue', 'niu', 'nu', '570', NULL),
('Norfolk Island', 'nfk', 'nf', '574', NULL),
('Northern Mariana Islands', 'mnp', 'mp', '580', NULL),
('Norway', 'nor', 'no', '578', NULL),
('Oman', 'omn', 'om', '512', NULL),
('Pakistan', 'pak', 'pk', '586', NULL),
('Palau', 'plw', 'pw', '585', NULL),
('Palestinian Territory, Occupied', 'pse', 'ps', '275', NULL),
('Panama', 'pan', 'pa', '591', NULL),
('Papua New Guinea', 'png', 'pg', '598', NULL),
('Paraguay', 'pry', 'py', '600', NULL),
('Peru', 'per', 'pe', '604', NULL),
('Philippines', 'phl', 'ph', '608', NULL),
('Pitcairn', 'pcn', 'pn', '612', NULL),
('Poland', 'pol', 'pl', '616', NULL),
('Portugal', 'prt', 'pt', '620', NULL),
('Puerto Rico', 'pri', 'pr', '630', NULL),
('Qatar', 'qat', 'qa', '634', NULL),
('Réunion', 'reu', 're', '638', NULL),
('Romania', 'rou', 'ro', '642', NULL),
('Russian Federation', 'rus', 'ru', '643', 1),
('Rwanda', 'rwa', 'rw', '646', NULL),
('Saint Helena, Ascension and Tristan da Cunha', 'shn', 'sh', '654', NULL),
('Saint Kitts and Nevis', 'kna', 'kn', '659', NULL),
('Saint Lucia', 'lca', 'lc', '662', NULL),
('Saint Pierre and Miquelon', 'spm', 'pm', '666', NULL),
('Saint Vincent and the Grenadines', 'vct', 'vc', '670', NULL),
('Samoa', 'wsm', 'ws', '882', NULL),
('San Marino', 'smr', 'sm', '674', NULL),
('Sao Tome and Principe', 'stp', 'st', '678', NULL),
('Saudi Arabia', 'sau', 'sa', '682', NULL),
('Senegal', 'sen', 'sn', '686', NULL),
('Serbia', 'srb', 'rs', '688', NULL),
('Seychelles', 'syc', 'sc', '690', NULL),
('Sierra Leone', 'sle', 'sl', '694', NULL),
('Singapore', 'sgp', 'sg', '702', NULL),
('Slovakia', 'svk', 'sk', '703', NULL),
('Slovenia', 'svn', 'si', '705', NULL),
('Solomon Islands', 'slb', 'sb', '090', NULL),
('Somalia', 'som', 'so', '706', NULL),
('South Africa', 'zaf', 'za', '710', NULL),
('South Georgia and the South Sandwich Islands', 'sgs', 'gs', '239', NULL),
('Spain', 'esp', 'es', '724', NULL),
('Sri Lanka', 'lka', 'lk', '144', NULL),
('Sudan', 'sdn', 'sd', '736', NULL),
('Suriname', 'sur', 'sr', '740', NULL),
('Svalbard and Jan Mayen', 'sjm', 'sj', '744', NULL),
('Swaziland', 'swz', 'sz', '748', NULL),
('Sweden', 'swe', 'se', '752', NULL),
('Switzerland', 'che', 'ch', '756', NULL),
('Syrian Arab Republic', 'syr', 'sy', '760', NULL),
('Taiwan, Province of China', 'twn', 'tw', '158', NULL),
('Tajikistan', 'tjk', 'tj', '762', NULL),
('Tanzania, United Republic of', 'tza', 'tz', '834', NULL),
('Thailand', 'tha', 'th', '764', NULL),
('Timor-Leste', 'tls', 'tl', '626', NULL),
('Togo', 'tgo', 'tg', '768', NULL),
('Tokelau', 'tkl', 'tk', '772', NULL),
('Tonga', 'ton', 'to', '776', NULL),
('Trinidad and Tobago', 'tto', 'tt', '780', NULL),
('Tunisia', 'tun', 'tn', '788', NULL),
('Turkey', 'tur', 'tr', '792', NULL),
('Turkmenistan', 'tkm', 'tm', '795', NULL),
('Turks and Caicos Islands', 'tca', 'tc', '796', NULL),
('Tuvalu', 'tuv', 'tv', '798', NULL),
('Uganda', 'uga', 'ug', '800', NULL),
('Ukraine', 'ukr', 'ua', '804', 1),
('United Arab Emirates', 'are', 'ae', '784', NULL),
('United Kingdom', 'gbr', 'gb', '826', NULL),
('United States', 'usa', 'us', '840', NULL),
('United States Minor Outlying Islands', 'umi', 'um', '581', NULL),
('Uruguay', 'ury', 'uy', '858', NULL),
('Uzbekistan', 'uzb', 'uz', '860', NULL),
('Vanuatu', 'vut', 'vu', '548', NULL),
('Venezuela, Bolivarian Republic of', 'ven', 've', '862', NULL),
('Viet Nam', 'vnm', 'vn', '704', NULL),
('Virgin Islands, British', 'vgb', 'vg', '092', NULL),
('Virgin Islands, U.S.', 'vir', 'vi', '850', NULL),
('Wallis and Futuna', 'wlf', 'wf', '876', NULL),
('Western Sahara', 'esh', 'eh', '732', NULL),
('Yemen', 'yem', 'ye', '887', NULL),
('Zambia', 'zmb', 'zm', '894', NULL),
('Zimbabwe', 'zwe', 'zw', '716', NULL),
('Abkhazia', 'abh', 'ab', '895', NULL),
('Bonaire, Sint Eustatius and Saba', 'bes', 'bq', '535', NULL),
('Guernsey', 'ggy', 'gg', '831', NULL),
('Jersey', 'jey', 'je', '832', NULL),
('Curaçao', 'cuw', 'cw', '531', NULL),
('Isle of Man', 'imn', 'im', '833', NULL),
('Saint Barthélemy', 'blm', 'bl', '652', NULL),
('Saint Martin (French Part)', 'maf', 'mf', '663', NULL),
('Sint Maarten', 'sxm', 'sx', '534', NULL),
('South Ossetia', 'ost', 'os', '896', NULL),
('South Sudan', 'ssd', 'ss', '728', NULL);
