INSERT IGNORE INTO wa_region (country_iso3, code, name, fav_sort, region_center) VALUES

-- USA
('usa', 'AL', 'Alabama', null, 'Montgomery'),
('usa', 'AK', 'Alaska', null, 'Juneau'),
('usa', 'AZ', 'Arizona', null, 'Phoenix'),
('usa', 'AR', 'Arkansas', null, 'Little Rock'),
('usa', 'CA', 'California', null, 'Sacramento'),
('usa', 'CO', 'Colorado', null, 'Denver'),
('usa', 'CT', 'Connecticut', null, 'Hartford'),
('usa', 'DE', 'Delaware', null, 'Dover'),
('usa', 'DC', 'District of Columbia', null, 'Washington DC'),
('usa', 'FL', 'Florida', null, 'Tallahassee'),
('usa', 'GA', 'Georgia', null, 'Atlanta'),
('usa', 'HI', 'Hawaii', null, 'Honolulu'),
('usa', 'ID', 'Idaho', null, 'Boise'),
('usa', 'IL', 'Illinois', null, 'Springfield'),
('usa', 'IN', 'Indiana', null, 'Indianapolis'),
('usa', 'IA', 'Iowa', null, 'Des Moines'),
('usa', 'KS', 'Kansas', null, 'Topeka'),
('usa', 'KY', 'Kentucky', null, 'Frankfort'),
('usa', 'LA', 'Louisiana', null, 'Baton Rouge'),
('usa', 'ME', 'Maine', null, 'Augusta'),
('usa', 'MD', 'Maryland', null, 'Annapolis'),
('usa', 'MA', 'Massachusetts', null, 'Boston'),
('usa', 'MI', 'Michigan', null, 'Lansing'),
('usa', 'MN', 'Minnesota', null, 'Saint Paul'),
('usa', 'MS', 'Mississippi', null, 'Jackson'),
('usa', 'MO', 'Missouri', null, 'Jefferson City'),
('usa', 'MT', 'Montana', null, 'Helena'),
('usa', 'NE', 'Nebraska', null, 'Lincoln'),
('usa', 'NV', 'Nevada', null, 'Carson City'),
('usa', 'NH', 'New Hampshire', null, 'Concord'),
('usa', 'NJ', 'New Jersey', null, 'Trenton'),
('usa', 'NM', 'New Mexico', null, 'Santa Fe'),
('usa', 'NY', 'New York', null, 'Albany'),
('usa', 'NC', 'North Carolina', null, 'Rayleigh'),
('usa', 'ND', 'North Dakota', null, 'Bismarck'),
('usa', 'OH', 'Ohio', null, 'Columbus'),
('usa', 'OK', 'Oklahoma', null, 'Oklahoma City'),
('usa', 'OR', 'Oregon', null, 'Salem'),
('usa', 'PA', 'Pennsylvania', null, 'Harrisburg'),
('usa', 'RI', 'Rhode Island', null, 'Providence'),
('usa', 'SC', 'South Carolina', null, 'Columbia'),
('usa', 'SD', 'South Dakota', null, 'Pierre'),
('usa', 'TN', 'Tennessee', null, 'Nashville'),
('usa', 'TX', 'Texas', null, 'Austin'),
('usa', 'UT', 'Utah', null, 'Salt Lake City'),
('usa', 'VT', 'Vermont', null, 'Montpelier'),
('usa', 'VA', 'Virginia', null, 'Richmond'),
('usa', 'WA', 'Washington', null, 'Olympia'),
('usa', 'WV', 'West Virginia', null, 'Charleston'),
('usa', 'WI', 'Wisconsin', null, 'Madison'),
('usa', 'WY', 'Wyoming', null, 'Cheyenne'),

-- CANADA
('can', '10', 'Newfoundland', null, null),
('can', '11', 'Prince Edward Island', null, null),
('can', '12', 'Nova Scotia', null, null),
('can', '13', 'New Brunswick', null, null),
('can', '24', 'Quebec', null, null),
('can', '35', 'Ontario', null, null),
('can', '46', 'Manitoba', null, null),
('can', '47', 'Saskatchewan', null, null),
('can', '48', 'Alberta', null, null),
('can', '59', 'British Columbia', null, null),
('can', '60', 'Yukon', null, null),
('can', '61', 'Northwest Territories', null, null),
('can', '62', 'Nunavut', null, null),

-- RUSSIA
('rus', '01', 'Адыгея республика', null, null),
('rus', '04', 'Алтай республика', null, null),
('rus', '22', 'Алтайский край', null, null),
('rus', '28', 'Амурская область', null, null),
('rus', '29', 'Архангельская область', null, null),
('rus', '30', 'Астраханская область', null, null),
('rus', '02', 'Башкортостан республика', null, null),
('rus', '31', 'Белгородская область', null, null),
('rus', '32', 'Брянская область', null, null),
('rus', '03', 'Бурятия республика', null, null),
('rus', '33', 'Владимирская область', null, null),
('rus', '34', 'Волгоградская область', null, null),
('rus', '35', 'Вологодская область', null, null),
('rus', '36', 'Воронежская область', null, null),
('rus', '05', 'Дагестан республика', null, null),
('rus', '80', 'Донецкая Народная Республика', null, null),
('rus', '79', 'Еврейская автономная область', null, null),
('rus', '75', 'Забайкальский край', null, null),
('rus', '85', 'Запорожская область', null, null),
('rus', '37', 'Ивановская область', null, null),
('rus', '06', 'Ингушетия республика', null, null),
('rus', '38', 'Иркутская область', null, null),
('rus', '07', 'Кабардино-Балкарская республика', null, null),
('rus', '09', 'Карачаево-Черкесская республика', null, null),
('rus', '39', 'Калининградская область', null, null),
('rus', '08', 'Калмыкия республика', null, null),
('rus', '40', 'Калужская область', null, null),
('rus', '41', 'Камчатский край', null, null),
('rus', '10', 'Карелия республика', null, null),
('rus', '42', 'Кемеровская область', null, null),
('rus', '43', 'Кировская область', null, null),
('rus', '11', 'Коми республика', null, null),
('rus', '44', 'Костромская область', null, null),
('rus', '23', 'Краснодарский край', null, null),
('rus', '24', 'Красноярский край', null, null),
('rus', '91', 'Крым республика', null, null),
('rus', '45', 'Курганская область', null, null),
('rus', '46', 'Курская область', null, null),
('rus', '47', 'Ленинградская область', null, null),
('rus', '48', 'Липецкая область', null, null),
('rus', '81', 'Луганская Народная Республика', null, null),
('rus', '49', 'Магаданская область', null, null),
('rus', '12', 'Марий Эл республика', null, null),
('rus', '50', 'Московская область', null, null),
('rus', '77', 'Москва', null, 'Москва'),
('rus', '13', 'Мордовия республика', null, null),
('rus', '51', 'Мурманская область', null, null),
('rus', '83', 'Ненецкий автономный округ', null, null),
('rus', '52', 'Нижегородская область', null, null),
('rus', '53', 'Новгородская область', null, null),
('rus', '54', 'Новосибирская область', null, null),
('rus', '55', 'Омская область', null, null),
('rus', '56', 'Оренбургская область', null, null),
('rus', '57', 'Орловская область', null, null),
('rus', '58', 'Пензенская область', null, null),
('rus', '59', 'Пермский край', null, null),
('rus', '25', 'Приморский край', null, null),
('rus', '60', 'Псковская область', null, null),
('rus', '61', 'Ростовская область', null, null),
('rus', '62', 'Рязанская область', null, null),
('rus', '63', 'Самарская область', null, null),
('rus', '78', 'Санкт-Петербург', null, 'Санкт-Петербург'),
('rus', '64', 'Саратовская область', null, null),
('rus', '14', 'Саха (Якутия) республика', null, null),
('rus', '65', 'Сахалинская область', null, null),
('rus', '66', 'Свердловская область', null, null),
('rus', '92', 'Севастополь', null, 'Севастополь'),
('rus', '15', 'Северная Осетия-Алания', null, null),
('rus', '67', 'Смоленская область', null, null),
('rus', '26', 'Ставропольский край', null, null),
('rus', '68', 'Тамбовская область', null, null),
('rus', '16', 'Татарстан республика', null, null),
('rus', '69', 'Тверская область', null, null),
('rus', '70', 'Томская область', null, null),
('rus', '71', 'Тульская область', null, null),
('rus', '72', 'Тюменская область', null, null),
('rus', '17', 'Тыва республика', null, null),
('rus', '18', 'Удмуртская республика', null, null),
('rus', '73', 'Ульяновская область', null, null),
('rus', '27', 'Хабаровский край', null, null),
('rus', '19', 'Хакасия республика', null, null),
('rus', '86', 'Ханты-Мансийский-Югра автономный округ', null, null),
('rus', '84', 'Херсонская область', null, null),
('rus', '74', 'Челябинская область', null, null),
('rus', '20', 'Чеченская республика', null, null),
('rus', '21', 'Чувашская республика', null, null),
('rus', '87', 'Чукотский автономный округ', null, null),
('rus', '89', 'Ямало-Ненецкий автономный округ', null, null),
('rus', '76', 'Ярославская область', null, null),

-- UKRAINE
('ukr', '01', 'Автономна Республіка Крим', null, null),
('ukr', '02', 'Вінницька область', null, null),
('ukr', '03', 'Волинська область', null, null),
('ukr', '04', 'Дніпропетровська область', null, null),
('ukr', '05', 'Донецька область', null, null),
('ukr', '06', 'Житомирська область', null, null),
('ukr', '07', 'Закарпатська область', null, null),
('ukr', '08', 'Запорізька область', null, null),
('ukr', '09', 'Івано-Франківська область', null, null),
('ukr', '10', 'Київська область', null, null),
('ukr', '11', 'місто Київ', null, null),
('ukr', '12', 'Кіровоградська область', null, null),
('ukr', '13', 'Луганська область', null, null),
('ukr', '14', 'Львівська область', null, null),
('ukr', '15', 'Миколаївська область', null, null),
('ukr', '16', 'Одеська область', null, null),
('ukr', '17', 'Полтавська область', null, null),
('ukr', '18', 'Рівненська область', null, null),
('ukr', '19', 'Сумська область', null, null),
('ukr', '20', 'Тернопільська область', null, null),
('ukr', '21', 'Харківська область', null, null),
('ukr', '22', 'Херсонська область', null, null),
('ukr', '23', 'Хмельницька область', null, null),
('ukr', '24', 'Черкаська область', null, null),
('ukr', '25', 'Чернігівська область', null, null),
('ukr', '26', 'Чернівецька область', null, null),

-- BELARUS
('blr', '01', 'Брэсцкая вобласць', null, 'Брэст'),
('blr', '02', 'Віцебская вобласць', null, 'Віцебск'),
('blr', '03', 'Гомельская вобласць', null, 'Гомель'),
('blr', '04', 'Гродзенская вобласць', null, 'Гродна'),
('blr', '05', 'Мінская вобласць', null, 'Мінск'),
('blr', '06', 'Магілёўская вобласць', null, 'Магілёў'),
('blr', '07', 'Мінск', null, 'Мінск'),

-- KAZAKHSTAN
('kaz', '01', 'Астана', null, 'Астана'),
('kaz', '02', 'Алматы', null, 'Алматы'),
('kaz', '03', 'Ақмола облысы', null, 'Көкшетау'),
('kaz', '04', 'Ақтөбе облысы', null, 'Ақтөбе'),
('kaz', '05', 'Алматы облысы', null, 'Қонаев'),
('kaz', '06', 'Атырау облысы', null, 'Атырау'),
('kaz', '07', 'Батыс Қазақстан облысы', null, 'Орал'),
('kaz', '08', 'Жамбыл облысы', null, 'Тараз'),
('kaz', '09', 'Қарағанды облысы', null, 'Қарағанды'),
('kaz', '10', 'Қостанай облысы', null, 'Қостанай'),
('kaz', '11', 'Қызылорда облысы', null, 'Қызылорда'),
('kaz', '12', 'Маңғыстау облысы', null, 'Ақтау'),
('kaz', '13', 'Түркістан облысы', null, 'Түркістан'),
('kaz', '14', 'Павлодар облысы', null, 'Павлодар'),
('kaz', '15', 'Солтүстік Қазақстан облысы', null, 'Петропавл'),
('kaz', '16', 'Шығыс Қазақстан облысы', null, 'Өскемен'),
('kaz', '17', 'Шымкент', null, 'Шымкент'),
('kaz', '18', 'Абай облысы', null, 'Семей'),
('kaz', '19', 'Жетісу облысы', null, 'Талдықорған'),
('kaz', '20', 'Ұлытау облысы', null, 'Жезқазған'),

-- ARMENIA
('arm', '01', 'Арагацотнская область', null, 'Аштарак'),
('arm', '02', 'Араратская область', null, 'Арташат'),
('arm', '03', 'Армавирская область', null, 'Армавир'),
('arm', '04', 'Вайоцдзорская область', null, 'Ехегнадзор'),
('arm', '05', 'Гехаркуникская область', null, 'Гавар'),
('arm', '06', 'Котайкская область', null, 'Раздан'),
('arm', '07', 'Лорийская область', null, 'Ванадзор'),
('arm', '08', 'Сюникская область', null, 'Капан'),
('arm', '09', 'Тавушская область', null, 'Иджеван'),
('arm', '10', 'Ширакская область', null, 'Гюмри'),
('arm', '11', 'Ереван', null, 'Ереван'),

-- GEORGIA
('geo', 'GE-AB', 'Абхазская Автономная Республика', null, 'Сухуми'),
('geo', 'GE-SZ', 'Самегрело-Верхняя Сванетия', null, 'Зугдиди'),
('geo', 'GE-GU', 'Гурия', null, 'Озургети'),
('geo', 'GE-AJ', 'Аджарская Автономная Республика', null, 'Батуми'),
('geo', 'GE-RL', 'Рача-Лечхуми и Нижняя Сванетия', null, 'Амбролаури'),
('geo', 'GE-IM', 'Имеретия', null, 'Кутаиси'),
('geo', 'GE-SJ', 'Самцхе-Джавахетия', null, 'Ахалцихе'),
('geo', 'GE-SK', 'Шида-Картли', null, 'Гори'),
('geo', 'GE-MM', 'Мцхета-Мтианети', null, 'Мцхета'),
('geo', 'GE-KK', 'Квемо-Картли', null, 'Рустави'),
('geo', 'GE-KA', 'Кахетия', null, 'Телави'),
('geo', 'GE-TB', 'Тбилиси', null, 'Тбилиси'),

-- CHINA
('chn', '11', 'Beijing', null, null),
('chn', '12', 'Tianjin', null, null),
('chn', '13', 'Hebei', null, null),
('chn', '14', 'Shanxi', null, null),
('chn', '21', 'Liaoning', null, null),
('chn', '15', 'Inner Mongolia', null, null),
('chn', '22', 'Jilin', null, null),
('chn', '23', 'Heilongjiang', null, null),
('chn', '34', 'Anhui', null, null),
('chn', '33', 'Zhejiang', null, null),
('chn', '36', 'Jiangxi', null, null),
('chn', '31', 'Shanghai', null, null),
('chn', '35', 'Fujian', null, null),
('chn', '32', 'Jiangsu', null, null),
('chn', '37', 'Shandong', null, null),
('chn', '46', 'Hainan', null, null),
('chn', '42', 'Hubei', null, null),
('chn', '43', 'Hunan', null, null),
('chn', '41', 'Henan', null, null),
('chn', '44', 'Guangdong', null, null),
('chn', '45', 'Guangxi', null, null),
('chn', '50', 'Chongqing', null, null),
('chn', '51', 'Sichuan', null, null),
('chn', '61', 'Shaanxi', null, null),
('chn', '53', 'Yunnan', null, null),
('chn', '54', 'Xizang', null, null),
('chn', '62', 'Gansu', null, null),
('chn', '52', 'Guizhou', null, null),
('chn', '64', 'Ningxia', null, null),
('chn', '63', 'Qinghai', null, null),
('chn', '65', 'Xinjiang', null, null),

-- INDIA
('ind', '37', 'Andhra Pradesh', null, 'Amaravati'),
('ind', '12', 'Arunachal Pradesh', null, 'Itanagar'),
('ind', '18', 'Assam', null, 'Dispur'),
('ind', '10', 'Bihar', null, 'Patna'),
('ind', '22', 'Chhattisgarh', null, 'Raipur'),
('ind', '7', 'Delhi', null, 'Delhi'),
('ind', '30', 'Goa', null, 'Panaji'),
('ind', '24', 'Gujarat', null, 'Gandhinagar'),
('ind', '6', 'Haryana', null, 'Chandigarh'),
('ind', '2', 'Himachal Pradesh', null, 'Shimla'),
('ind', '1', 'Jammu and Kashmir', null, 'Srinagar'),
('ind', '20', 'Jharkhand', null, 'Ranchi'),
('ind', '29', 'Karnataka', null, 'Bengaluru'),
('ind', '32', 'Kerala', null, 'Thiruvananthapuram'),
('ind', '31', 'Lakshadweep Islands', null, 'Kavaratti'),
('ind', '23', 'Madhya Pradesh', null, 'Bhopal'),
('ind', '27', 'Maharashtra', null, 'Mumbai'),
('ind', '14', 'Manipur', null, 'Imphal'),
('ind', '17', 'Meghalaya', null, 'Shillong'),
('ind', '15', 'Mizoram', null, 'Aizawl'),
('ind', '13', 'Nagaland', null, 'Kohima'),
('ind', '21', 'Odisha', null, 'Bhubaneswar'),
('ind', '34', 'Pondicherry', null, 'Pondicherry'),
('ind', '3', 'Punjab', null, 'Chandigarh'),
('ind', '8', 'Rajasthan', null, 'Jaipur'),
('ind', '11', 'Sikkim', null, 'Gangtok'),
('ind', '33', 'Tamil Nadu', null, 'Chennai'),
('ind', '36', 'Telangana', null, 'Hyderabad'),
('ind', '16', 'Tripura', null, 'Agartala'),
('ind', '9', 'Uttar Pradesh', null, 'Lucknow'),
('ind', '5', 'Uttarakhand', null, 'Dehradun'),
('ind', '19', 'West Bengal', null, 'Kolkata'),

-- AUSTRALIA
('aus', '1', 'New South Wales', null, 'Sydney'),
('aus', '2', 'Victoria', null, 'Melbourne'),
('aus', '3', 'Queensland', null, 'Brisbane'),
('aus', '4', 'South Australia', null, 'Adelaide'),
('aus', '5', 'Western Australia', null, 'Perth'),
('aus', '6', 'Tasmania', null, 'Hobart'),
('aus', '7', 'Northern Territory', null, 'Darwin'),
('aus', '8', 'Australian Capital Territory', null, 'Canberra'),
('aus', '9', 'Other Territories', null, null),

-- GERMANY
('deu', '01', 'Schleswig-Holstein', null, null),
('deu', '02', 'Hamburg', null, null),
('deu', '03', 'Niedersachsen', null, null),
('deu', '04', 'Bremen', null, null),
('deu', '05', 'Nordrhein-Westfalen', null, null),
('deu', '06', 'Hessen', null, null),
('deu', '07', 'Rheinland-Pfalz', null, null),
('deu', '08', 'Baden-Württemberg', null, null),
('deu', '09', 'Bayern', null, null),
('deu', '10', 'Saarland', null, null),
('deu', '11', 'Berlin', null, null),
('deu', '12', 'Brandenburg', null, null),
('deu', '13', 'Mecklenburg-Vorpommern', null, null),
('deu', '14', 'Sachsen', null, null),
('deu', '15', 'Sachsen-Anhalt', null, null),
('deu', '16', 'Thueringen', null, null),

-- BELGIUM
('bel', '11', 'Antwerpen', null, null),
('bel', '12', 'Mechelen', null, null),
('bel', '13', 'Turnhout', null, null),
('bel', '21', 'Brussel-Hoofdstad', null, null),
('bel', '23', 'Halle-Vilvoorde', null, null),
('bel', '24', 'Leuven', null, null),
('bel', '25', 'Nijvel', null, null),
('bel', '31', 'Brugge', null, null),
('bel', '32', 'Diksmuide', null, null),
('bel', '33', 'Ieper', null, null),
('bel', '34', 'Kortrijk', null, null),
('bel', '35', 'Oostende', null, null),
('bel', '36', 'Roeselare', null, null),
('bel', '37', 'Tielt', null, null),
('bel', '38', 'Veurne', null, null),
('bel', '41', 'Aalst', null, null),
('bel', '42', 'Dendermonde', null, null),
('bel', '43', 'Eeklo', null, null),
('bel', '44', 'Gent', null, null),
('bel', '45', 'Oudenaarde', null, null),
('bel', '46', 'Sint-Niklaas', null, null),
('bel', '51', 'Aat', null, null),
('bel', '52', 'Charleroi', null, null),
('bel', '53', 'Bergen', null, null),
('bel', '54', 'Moeskroen', null, null),
('bel', '55', 'Zinnik', null, null),
('bel', '56', 'Thuin', null, null),
('bel', '57', 'Doornik', null, null),
('bel', '61', 'Hoei', null, null),
('bel', '62', 'Luik', null, null),
('bel', '63', 'Verviers', null, null),
('bel', '64', 'Borgworm', null, null),
('bel', '71', 'Hasselt', null, null),
('bel', '72', 'Maaseik', null, null),
('bel', '73', 'Tongeren', null, null),
('bel', '81', 'Aarlen', null, null),
('bel', '82', 'Bastenaken', null, null),
('bel', '83', 'Marche-en-Famenne', null, null),
('bel', '84', 'Neufchâteau', null, null),
('bel', '85', 'Virton', null, null),
('bel', '91', 'Dinant', null, null),
('bel', '92', 'Namen', null, null),
('bel', '93', 'Philippeville', null, null),

-- DENMARK
('dnk', '101', 'København', null, null),
('dnk', '102', 'Frederiksberg', null, null),
('dnk', '150', 'Københavns Amt', null, null),
('dnk', '200', 'Frederiksborg Amt', null, null),
('dnk', '250', 'Roskilde Amt', null, null),
('dnk', '300', 'Vestsjællands Amt', null, null),
('dnk', '350', 'Storstrøms Amt', null, null),
('dnk', '400', 'Bornholms Amt', null, null),
('dnk', '420', 'Fyns Amt', null, null),
('dnk', '500', 'Sønderjyllands Amt', null, null),
('dnk', '550', 'Ribe Amt', null, null),
('dnk', '600', 'Vejle Amt', null, null),
('dnk', '650', 'Ringkøbing Amt', null, null),
('dnk', '700', 'Århus Amt', null, null),
('dnk', '760', 'Viborg Amt', null, null),
('dnk', '800', 'Nordjyllands Amt', null, null),

-- FRANCE
('fra', '01', 'Ain', null, null),
('fra', '02', 'Aisne', null, null),
('fra', '03', 'Allier', null, null),
('fra', '04', 'Alpes-de-Haute-Provence', null, null),
('fra', '05', 'Hautes-Alpes', null, null),
('fra', '06', 'Alpes-Maritimes', null, null),
('fra', '07', 'Ardèche', null, null),
('fra', '08', 'Ardennes', null, null),
('fra', '09', 'Ariège', null, null),
('fra', '10', 'Aube', null, null),
('fra', '11', 'Aude', null, null),
('fra', '12', 'Aveyron', null, null),
('fra', '13', 'Bouches-du-Rhône', null, null),
('fra', '14', 'Calvados', null, null),
('fra', '15', 'Cantal', null, null),
('fra', '16', 'Charente', null, null),
('fra', '17', 'Charente-Maritime', null, null),
('fra', '18', 'Cher', null, null),
('fra', '19', 'Corrèze', null, null),
('fra', '21', 'Côte-d''Or', null, null),
('fra', '22', 'Côtes-du-Nord', null, null),
('fra', '23', 'Creuse', null, null),
('fra', '24', 'Dordogne', null, null),
('fra', '25', 'Doubs', null, null),
('fra', '26', 'Drôme', null, null),
('fra', '27', 'Eure', null, null),
('fra', '28', 'Eure-et-Loir', null, null),
('fra', '29', 'Finistère', null, null),
('fra', '30', 'Gard', null, null),
('fra', '31', 'Haute-Garonne', null, null),
('fra', '32', 'Gers', null, null),
('fra', '33', 'Gironde', null, null),
('fra', '34', 'Hérault', null, null),
('fra', '35', 'Ille-et-Vilaine', null, null),
('fra', '36', 'Indre', null, null),
('fra', '37', 'Indre-et-Loire', null, null),
('fra', '38', 'Isère', null, null),
('fra', '39', 'Jura', null, null),
('fra', '40', 'Landes', null, null),
('fra', '41', 'Loir-et-Cher', null, null),
('fra', '42', 'Loire', null, null),
('fra', '43', 'Haute-Loire', null, null),
('fra', '44', 'Loire-Atlantique', null, null),
('fra', '45', 'Loiret', null, null),
('fra', '46', 'Lot', null, null),
('fra', '47', 'Lot-et-Garonne', null, null),
('fra', '48', 'Lozère', null, null),
('fra', '49', 'Maine-et-Loire', null, null),
('fra', '50', 'Manche', null, null),
('fra', '51', 'Marne', null, null),
('fra', '52', 'Haute-Marne', null, null),
('fra', '53', 'Mayenne', null, null),
('fra', '54', 'Meurthe-et-Moselle', null, null),
('fra', '55', 'Meuse', null, null),
('fra', '56', 'Morbihan', null, null),
('fra', '57', 'Moselle', null, null),
('fra', '58', 'Nièvre', null, null),
('fra', '59', 'Nord', null, null),
('fra', '60', 'Oise', null, null),
('fra', '61', 'Orne', null, null),
('fra', '62', 'Pas-de-Calais', null, null),
('fra', '63', 'Puy-de-Dôme', null, null),
('fra', '64', 'Pyrénées-Atlantiques', null, null),
('fra', '65', 'Hautes-Pyrénées', null, null),
('fra', '66', 'Pyrénées-Orientales', null, null),
('fra', '67', 'Bas-Rhin', null, null),
('fra', '68', 'Haut-Rhin', null, null),
('fra', '69', 'Rhône', null, null),
('fra', '70', 'Haute-Saône', null, null),
('fra', '71', 'Saône-et-Loire', null, null),
('fra', '72', 'Sarthe', null, null),
('fra', '73', 'Savoie', null, null),
('fra', '74', 'Haute-Savoie', null, null),
('fra', '75', 'Ville-de-Paris', null, null),
('fra', '76', 'Seine-Maritime', null, null),
('fra', '77', 'Seine-et-Marne', null, null),
('fra', '78', 'Yvelines', null, null),
('fra', '79', 'Deux-Sèvres', null, null),
('fra', '80', 'Somme', null, null),
('fra', '81', 'Tarn', null, null),
('fra', '82', 'Tarn-et-Garonne', null, null),
('fra', '83', 'Var', null, null),
('fra', '84', 'Vaucluse', null, null),
('fra', '85', 'Vendée', null, null),
('fra', '86', 'Vienne', null, null),
('fra', '87', 'Haute-Vienne', null, null),
('fra', '88', 'Vosges', null, null),
('fra', '89', 'Yonne', null, null),
('fra', '90', 'Territoire-de-Belfort', null, null),
('fra', '91', 'Essonne', null, null),
('fra', '92', 'Hauts-de-Seine', null, null),
('fra', '93', 'Seine-Saint-Denis', null, null),
('fra', '94', 'Val-de-Marne', null, null),
('fra', '95', 'Val-d''Oise', null, null),
('fra', '99', 'Monaco', null, null),
('fra', '2A', 'Corse-du-Sud', null, null),
('fra', '2B', 'Haute-Corse', null, null),

-- GREECE
('grc', '01', 'Aitolias Kai Akarnanias', null, null),
('grc', '03', 'Voiotia', null, null),
('grc', '04', 'Eivoias', null, null),
('grc', '05', 'Evritania', null, null),
('grc', '06', 'Fthiotida', null, null),
('grc', '07', 'Fokida', null, null),
('grc', '11', 'Argolidos', null, null),
('grc', '12', 'Arkadias', null, null),
('grc', '13', 'Ahaia', null, null),
('grc', '14', 'Ilia', null, null),
('grc', '15', 'Korinthos', null, null),
('grc', '16', 'Lakonia', null, null),
('grc', '17', 'Messinia', null, null),
('grc', '21', 'Zakinthos', null, null),
('grc', '22', 'Kerkira (Corfu)', null, null),
('grc', '23', 'Kefallonia', null, null),
('grc', '24', 'Lefkada', null, null),
('grc', '31', 'Arta', null, null),
('grc', '32', 'Thesprotia', null, null),
('grc', '33', 'Ioannina', null, null),
('grc', '34', 'Preveza', null, null),
('grc', '41', 'Karditsa', null, null),
('grc', '42', 'Larissa', null, null),
('grc', '43', 'Magnisias', null, null),
('grc', '44', 'Trikala', null, null),
('grc', '51', 'Grevena', null, null),
('grc', '52', 'Drama', null, null),
('grc', '53', 'Imathia', null, null),
('grc', '54', 'Thessaloniki', null, null),
('grc', '55', 'Kavala', null, null),
('grc', '56', 'Kastoria', null, null),
('grc', '57', 'Kilkis', null, null),
('grc', '58', 'Kozani', null, null),
('grc', '59', 'Pela', null, null),
('grc', '61', 'Pieria', null, null),
('grc', '62', 'Seres', null, null),
('grc', '63', 'Florina', null, null),
('grc', '64', 'Halkida', null, null),
('grc', '65', 'Agion Opos', null, null),
('grc', '71', 'Evros', null, null),
('grc', '72', 'Xanthi', null, null),
('grc', '73', 'Rodopi', null, null),
('grc', '81', 'Dodekanissa (Dodecanese)', null, null),
('grc', '82', 'Kiklades (Cyclades)', null, null),
('grc', '83', 'Lesvos', null, null),
('grc', '84', 'Samos', null, null),
('grc', '85', 'Hios', null, null),
('grc', '91', 'Iraklio', null, null),
('grc', '92', 'Lasithioi', null, null),
('grc', '93', 'Rethimno', null, null),
('grc', '94', 'Hania', null, null),
('grc', 'A1', 'Athina (Athens)', null, null),
('grc', 'A2', 'Anatoliki Attiki', null, null),
('grc', 'A3', 'Ditiki Attiki', null, null),
('grc', 'A4', 'Peiria', null, null),

-- INDONESIA
('idn', '11', 'Nanggroe Aceh Darussalam', null, null),
('idn', '12', 'Sumatera Utara', null, null),
('idn', '13', 'Sumatera Barat', null, null),
('idn', '14', 'Riau', null, null),
('idn', '15', 'Jambi', null, null),
('idn', '16', 'Sumatera Selatan', null, null),
('idn', '17', 'Bengkulu', null, null),
('idn', '18', 'Lampung', null, null),
('idn', '19', 'Kepulauan Bangka Belitung', null, null),
('idn', '21', 'Kepulauan Riau', null, null),
('idn', '31', 'DKI Jakarta', null, null),
('idn', '32', 'Jawa Barat', null, null),
('idn', '33', 'Jawa Tengah', null, null),
('idn', '34', 'DI Yogyakarta', null, null),
('idn', '35', 'Jawa Timur', null, null),
('idn', '36', 'Banten', null, null),
('idn', '51', 'Bali', null, null),
('idn', '52', 'Nusa Tenggara Barat', null, null),
('idn', '53', 'Nusa Tenggara Timur', null, null),
('idn', '61', 'Kalimantan Barat', null, null),
('idn', '62', 'Kalimantan Tengah', null, null),
('idn', '63', 'Kalimantan Selatan', null, null),
('idn', '64', 'Kalimantan Timur', null, null),
('idn', '71', 'Sulawesi Utara', null, null),
('idn', '72', 'Sulawesi Tengah', null, null),
('idn', '73', 'Sulawesi Selatan', null, null),
('idn', '74', 'Sulawesi Tenggara', null, null),
('idn', '75', 'Gorontalo', null, null),
('idn', '76', 'Sulawesi Barat', null, null),
('idn', '81', 'Maluku', null, null),
('idn', '82', 'Maluku Utara', null, null),
('idn', '91', 'Papua Barat', null, null),
('idn', '94', 'Papua', null, null),

-- IRELAND
('irl', '01', 'Carlow', null, null),
('irl', '02', 'Dublin County Borough', null, null),
('irl', '03', 'South Dublin', null, null),
('irl', '04', 'Fingal', null, null),
('irl', '05', 'Dun Laoghaire-Rathdown', null, null),
('irl', '06', 'Kildare', null, null),
('irl', '07', 'Kilkenny', null, null),
('irl', '08', 'Laoighis', null, null),
('irl', '09', 'Longford', null, null),
('irl', '10', 'Louth', null, null),
('irl', '11', 'Meath', null, null),
('irl', '12', 'Offaly', null, null),
('irl', '13', 'Westmeath', null, null),
('irl', '14', 'Wexford', null, null),
('irl', '15', 'Wicklow', null, null),
('irl', '16', 'Clare', null, null),
('irl', '18', 'Cork County Borough', null, null),
('irl', '19', 'Cork', null, null),
('irl', '20', 'Kerry', null, null),
('irl', '22', 'Limerick County Borough', null, null),
('irl', '23', 'Limerick', null, null),
('irl', '24', 'Tipperary North Riding', null, null),
('irl', '25', 'Tipperay South Riding', null, null),
('irl', '27', 'Waterford County Borough', null, null),
('irl', '28', 'Waterford', null, null),
('irl', '29', 'Galway', null, null),
('irl', '30', 'Leitrim', null, null),
('irl', '31', 'Mayo', null, null),
('irl', '32', 'Roscommon', null, null),
('irl', '33', 'Sligo', null, null),
('irl', '34', 'Cavan', null, null),
('irl', '35', 'Donegal', null, null),
('irl', '36', 'Monaghan', null, null),
('irl', '37', 'Galway County Borough', null, null),

-- ISRAEL
('isr', '01', 'Akko', null, null),
('isr', '02', 'Ashqelon', null, null),
('isr', '03', 'Beer Sheva', null, null),
('isr', '04', 'Gaza Area', null, null),
('isr', '05', 'Golan', null, null),
('isr', '06', 'Hadera', null, null),
('isr', '07', 'Haifa', null, null),
('isr', '08', 'Jericho', null, null),
('isr', '09', 'Jerusalem', null, null),
('isr', '10', 'Kinneret', null, null),
('isr', '11', 'Petah Tiqwa', null, null),
('isr', '12', 'Ramla', null, null),
('isr', '13', 'Rehovot', null, null),
('isr', '14', 'Sharon', null, null),
('isr', '15', 'Tel Aviv', null, null),
('isr', '16', 'Yizreel', null, null),
('isr', '17', 'Zefat', null, null),

-- ITALY
('ita','001', 'Torino', null, null),
('ita','002', 'Vercelli', null, null),
('ita','003', 'Novara', null, null),
('ita','004', 'Cuneo', null, null),
('ita','005', 'Asti', null, null),
('ita','006', 'Alessandria', null, null),
('ita','007', 'Valle d''Aosta', null, null),
('ita','008', 'Imperia', null, null),
('ita','009', 'Savona', null, null),
('ita','010', 'Genova', null, null),
('ita','011', 'La Spezia', null, null),
('ita','012', 'Varese', null, null),
('ita','013', 'Como', null, null),
('ita','014', 'Sondrio', null, null),
('ita','015', 'Milano', null, null),
('ita','016', 'Bergamo', null, null),
('ita','017', 'Brescia', null, null),
('ita','018', 'Pavia', null, null),
('ita','019', 'Cremona', null, null),
('ita','020', 'Mantova', null, null),
('ita','021', 'Bolzano', null, null),
('ita','022', 'Trento', null, null),
('ita','023', 'Verona', null, null),
('ita','024', 'Vicenza', null, null),
('ita','025', 'Belluno', null, null),
('ita','026', 'Treviso', null, null),
('ita','027', 'Venezia', null, null),
('ita','028', 'Padova', null, null),
('ita','029', 'Rovigo', null, null),
('ita','030', 'Udine', null, null),
('ita','031', 'Gorizia', null, null),
('ita','032', 'Trieste', null, null),
('ita','033', 'Piacenza', null, null),
('ita','034', 'Parma', null, null),
('ita','035', 'Reggio Emilia', null, null),
('ita','036', 'Modena', null, null),
('ita','037', 'Bologna', null, null),
('ita','038', 'Ferrara', null, null),
('ita','039', 'Ravenna', null, null),
('ita','040', 'Forli-Cesena', null, null),
('ita','041', 'Pesaro E Urbino', null, null),
('ita','042', 'Ancona', null, null),
('ita','043', 'Macerata', null, null),
('ita','044', 'Ascoli Piceno', null, null),
('ita','045', 'Massa Carrara', null, null),
('ita','046', 'Lucca', null, null),
('ita','047', 'Pistoia', null, null),
('ita','048', 'Firenze', null, null),
('ita','049', 'Livorno', null, null),
('ita','050', 'Pisa', null, null),
('ita','051', 'Arezzo', null, null),
('ita','052', 'Siena', null, null),
('ita','053', 'Grosseto', null, null),
('ita','054', 'Perugia', null, null),
('ita','055', 'Terni', null, null),
('ita','056', 'Viterbo', null, null),
('ita','057', 'Rieti', null, null),
('ita','058', 'Roma', null, null),
('ita','059', 'Latina', null, null),
('ita','060', 'Frosinone', null, null),
('ita','061', 'Caserta', null, null),
('ita','062', 'Benevento', null, null),
('ita','063', 'Napoli', null, null),
('ita','064', 'Avellino', null, null),
('ita','065', 'Salerno', null, null),
('ita','066', 'L''Aquila', null, null),
('ita','067', 'Teramo', null, null),
('ita','068', 'Pescara', null, null),
('ita','069', 'Chieti', null, null),
('ita','070', 'Campobasso', null, null),
('ita','071', 'Foggia', null, null),
('ita','072', 'Bari', null, null),
('ita','073', 'Taranto', null, null),
('ita','074', 'Brindisi', null, null),
('ita','075', 'Lecce', null, null),
('ita','076', 'Potenza', null, null),
('ita','077', 'Matera', null, null),
('ita','078', 'Cosenza', null, null),
('ita','079', 'Catanzaro', null, null),
('ita','080', 'Reggio Calabria', null, null),
('ita','081', 'Trapani', null, null),
('ita','082', 'Palermo', null, null),
('ita','083', 'Messina', null, null),
('ita','084', 'Agrigento', null, null),
('ita','085', 'Caltanissetta', null, null),
('ita','086', 'Enna', null, null),
('ita','087', 'Catania', null, null),
('ita','088', 'Ragusa', null, null),
('ita','089', 'Siracusa', null, null),
('ita','090', 'Sassari', null, null),
('ita','091', 'Nuoro', null, null),
('ita','092', 'Cagliari', null, null),
('ita','093', 'Pordenone', null, null),
('ita','094', 'Isernia', null, null),
('ita','095', 'Oristano', null, null),
('ita','096', 'Biella', null, null),
('ita','097', 'Lecco', null, null),
('ita','098', 'Lodi', null, null),
('ita','099', 'Rimini', null, null),
('ita','100', 'Prato', null, null),
('ita','101', 'Crotone', null, null),
('ita','102', 'Vibo Valentia', null, null),
('ita','103', 'Verbano-Cusio-Ossola', null, null),
('ita','104', 'Olbia-Tempio', null, null),
('ita','105', 'Ogliastra', null, null),
('ita','106', 'Medio Campidano', null, null),
('ita','107', 'Carbonia-Iglesias', null, null),
('ita','888', 'Citta del Vaticano', null, null),
('ita','999', 'San Marino', null, null),

-- REPUBLIC OF KOREA
('kor', '11', 'Seoul', null, null),
('kor', '21', 'Busan', null, null),
('kor', '22', 'Daegu', null, null),
('kor', '23', 'Incheon', null, null),
('kor', '24', 'Gwangju', null, null),
('kor', '25', 'Daejeon', null, null),
('kor', '26', 'Ulsan', null, null),
('kor', '31', 'Gyeonggi-do', null, null),
('kor', '32', 'Gangwon-do', null, null),
('kor', '33', 'Chungcheongbuk-do', null, null),
('kor', '34', 'Chungcheongnam-do', null, null),
('kor', '35', 'Jeollabuk-do', null, null),
('kor', '36', 'Jeollanam-do', null, null),
('kor', '37', 'Gyeongsangbuk-do', null, null),
('kor', '38', 'Gyeongsangnam-do', null, null),
('kor', '39', 'Jeju-do', null, null),

-- TURKEY
('tur', '01', 'Adana', null, null),
('tur', '02', 'Adýyaman', null, null),
('tur', '03', 'Afyonkarahisar', null, null),
('tur', '04', 'Aðrý', null, null),
('tur', '05', 'Amasya', null, null),
('tur', '06', 'Ankara', null, null),
('tur', '07', 'Antalya', null, null),
('tur', '08', 'Artvin', null, null),
('tur', '09', 'Aydýn', null, null),
('tur', '10', 'Balýkesir', null, null),
('tur', '11', 'Bilecik', null, null),
('tur', '12', 'Bingöl', null, null),
('tur', '13', 'Bitlis', null, null),
('tur', '14', 'Bolu', null, null),
('tur', '15', 'Burdur', null, null),
('tur', '16', 'Bursa', null, null),
('tur', '17', 'Çanakkale', null, null),
('tur', '18', 'Çankýrý', null, null),
('tur', '19', 'Çorum', null, null),
('tur', '20', 'Denizli', null, null),
('tur', '21', 'Diyarbakýr', null, null),
('tur', '22', 'Edirne', null, null),
('tur', '23', 'Elazýð', null, null),
('tur', '24', 'Erzincan', null, null),
('tur', '25', 'Erzurum', null, null),
('tur', '26', 'Eskiþehir', null, null),
('tur', '27', 'Gaziantep', null, null),
('tur', '28', 'Giresun', null, null),
('tur', '29', 'Gümüþhane', null, null),
('tur', '30', 'Hakkari', null, null),
('tur', '31', 'Hatay', null, null),
('tur', '32', 'Isparta', null, null),
('tur', '33', 'Mersin', null, null),
('tur', '34', 'Ýstanbul', null, null),
('tur', '35', 'Ýzmir', null, null),
('tur', '36', 'Kars', null, null),
('tur', '37', 'Kastamonu', null, null),
('tur', '38', 'Kayseri', null, null),
('tur', '39', 'Kýrklareli', null, null),
('tur', '40', 'Kýrþehir', null, null),
('tur', '41', 'Kocaeli', null, null),
('tur', '42', 'Konya', null, null),
('tur', '43', 'Kütahya', null, null),
('tur', '44', 'Malatya', null, null),
('tur', '45', 'Manisa', null, null),
('tur', '46', 'Kahramanmaraþ', null, null),
('tur', '47', 'Mardin', null, null),
('tur', '48', 'Muðla', null, null),
('tur', '49', 'Muþ', null, null),
('tur', '50', 'Nevþehir', null, null),
('tur', '51', 'Niðde', null, null),
('tur', '52', 'Ordu', null, null),
('tur', '53', 'Rize', null, null),
('tur', '54', 'Sakarya', null, null),
('tur', '55', 'Samsun', null, null),
('tur', '56', 'Siirt', null, null),
('tur', '57', 'Sinop', null, null),
('tur', '58', 'Sivas', null, null),
('tur', '59', 'Tekirdað', null, null),
('tur', '60', 'Tokat', null, null),
('tur', '61', 'Trabzon', null, null),
('tur', '62', 'Tunceli', null, null),
('tur', '63', 'Þanlýurfa', null, null),
('tur', '64', 'Uþak', null, null),
('tur', '65', 'Van', null, null),
('tur', '66', 'Yozgat', null, null),
('tur', '67', 'Zonguldak', null, null),
('tur', '68', 'Aksaray', null, null),
('tur', '69', 'Bayburt', null, null),
('tur', '70', 'Karaman', null, null),
('tur', '71', 'Kýrýkkale', null, null),
('tur', '72', 'Batman', null, null),
('tur', '73', 'Þýrnak', null, null),
('tur', '74', 'Bartýn', null, null),
('tur', '75', 'Ardahan', null, null),
('tur', '76', 'Iðdýr', null, null),
('tur', '77', 'Yalova', null, null),
('tur', '78', 'Karabük', null, null),
('tur', '79', 'Kilis', null, null),
('tur', '80', 'Osmaniye', null, null),
('tur', '81', 'Düzce', null, null),

-- UNITED KINGDOM
('gbr', 'AB', 'Aberdeen', null, null),
('gbr', 'AL', 'St Albans', null, null),
('gbr', 'B', 'Birmingham', null, null),
('gbr', 'BA', 'Bath', null, null),
('gbr', 'BB', 'Blackburn', null, null),
('gbr', 'BD', 'Bradford', null, null),
('gbr', 'BH', 'Bournemouth', null, null),
('gbr', 'BL', 'Bolton', null, null),
('gbr', 'BN', 'Brighton', null, null),
('gbr', 'BR', 'Bromley', null, null),
('gbr', 'BS', 'Bristol', null, null),
('gbr', 'BT', 'Northern Ireland', null, null),
('gbr', 'CA', 'Carlisle', null, null),
('gbr', 'CB', 'Cambridge', null, null),
('gbr', 'CF', 'Cardiff', null, null),
('gbr', 'CH', 'Chester', null, null),
('gbr', 'CM', 'Chelmsford', null, null),
('gbr', 'CO', 'Colchester', null, null),
('gbr', 'CR', 'Croydon', null, null),
('gbr', 'CT', 'Canterbury', null, null),
('gbr', 'CV', 'Coventry', null, null),
('gbr', 'CW', 'Crewe', null, null),
('gbr', 'DA', 'Dartford', null, null),
('gbr', 'DD', 'Dundee', null, null),
('gbr', 'DE', 'Derby', null, null),
('gbr', 'DG', 'Dumfries', null, null),
('gbr', 'DH', 'Durham', null, null),
('gbr', 'DL', 'Darlington', null, null),
('gbr', 'DN', 'Doncaster', null, null),
('gbr', 'DT', 'Dorchester', null, null),
('gbr', 'DY', 'Dudley', null, null),
('gbr', 'E', 'London E', null, null),
('gbr', 'EC', 'London EC', null, null),
('gbr', 'EH', 'Edinburgh', null, null),
('gbr', 'EN', 'Enfield', null, null),
('gbr', 'EX', 'Exeter', null, null),
('gbr', 'FK', 'Falkirk', null, null),
('gbr', 'FY', 'Blackpool', null, null),
('gbr', 'G', 'Glasgow', null, null),
('gbr', 'GL', 'Gloucester', null, null),
('gbr', 'GU', 'Guildford', null, null),
('gbr', 'GY', 'Guernsey', null, null),
('gbr', 'HA', 'Harrow', null, null),
('gbr', 'HD', 'Huddersfield', null, null),
('gbr', 'HG', 'Harrogate', null, null),
('gbr', 'HP', 'Hemel Hempstead', null, null),
('gbr', 'HR', 'Hereford', null, null),
('gbr', 'HS', 'Outer Hebrides', null, null),
('gbr', 'HU', 'Hull', null, null),
('gbr', 'HX', 'Halifax', null, null),
('gbr', 'IC', 'Channel Islands', null, null),
('gbr', 'IG', 'Ilford', null, null),
('gbr', 'IM', 'Isle of Man', null, null),
('gbr', 'IP', 'Ipswich', null, null),
('gbr', 'IV', 'Inverness', null, null),
('gbr', 'JE', 'Jersey', null, null),
('gbr', 'KA', 'Kilmarnock', null, null),
('gbr', 'KT', 'Kingston upon Thames', null, null),
('gbr', 'KW', 'Kirkwall', null, null),
('gbr', 'KY', 'Kirkcaldy', null, null),
('gbr', 'L', 'Liverpool', null, null),
('gbr', 'LA', 'Lancaster', null, null),
('gbr', 'LD', 'Llandrindod Wells', null, null),
('gbr', 'LE', 'Leicester', null, null),
('gbr', 'LL', 'Llandudno', null, null),
('gbr', 'LN', 'Lincoln', null, null),
('gbr', 'LS', 'Leeds', null, null),
('gbr', 'LU', 'Luton', null, null),
('gbr', 'M', 'Manchester', null, null),
('gbr', 'ME', 'Medway', null, null),
('gbr', 'MK', 'Milton Keynes', null, null),
('gbr', 'ML', 'Motherwell', null, null),
('gbr', 'N', 'London N', null, null),
('gbr', 'NE', 'Newcastle upon Tyne', null, null),
('gbr', 'NG', 'Nottingham', null, null),
('gbr', 'NN', 'Northampton', null, null),
('gbr', 'NP', 'Newport', null, null),
('gbr', 'NR', 'Norwich', null, null),
('gbr', 'NW', 'London NW', null, null),
('gbr', 'OL', 'Oldham', null, null),
('gbr', 'OX', 'Oxford', null, null),
('gbr', 'PA', 'Paisley', null, null),
('gbr', 'PE', 'Peterborough', null, null),
('gbr', 'PH', 'Perth', null, null),
('gbr', 'PL', 'Plymouth', null, null),
('gbr', 'PO', 'Portsmouth', null, null),
('gbr', 'PR', 'Preston', null, null),
('gbr', 'RG', 'Reading', null, null),
('gbr', 'RH', 'Redhill', null, null),
('gbr', 'RM', 'Romford', null, null),
('gbr', 'S', 'Sheffield', null, null),
('gbr', 'SA', 'Swansea', null, null),
('gbr', 'SE', 'London SE', null, null),
('gbr', 'SG', 'Stevenage', null, null),
('gbr', 'SK', 'Stockport', null, null),
('gbr', 'SL', 'Slough', null, null),
('gbr', 'SM', 'Sutton', null, null),
('gbr', 'SN', 'Swindon', null, null),
('gbr', 'SO', 'Southampton', null, null),
('gbr', 'SP', 'Salisbury', null, null),
('gbr', 'SR', 'Sunderland', null, null),
('gbr', 'SS', 'Southend-on-Sea', null, null),
('gbr', 'ST', 'Stoke-on-Trent', null, null),
('gbr', 'SW', 'London SW', null, null),
('gbr', 'SY', 'Shrewsbury', null, null),
('gbr', 'TA', 'Taunton', null, null),
('gbr', 'TD', 'Galashiels', null, null),
('gbr', 'TF', 'Telford', null, null),
('gbr', 'TN', 'Tonbridge', null, null),
('gbr', 'TQ', 'Torquay', null, null),
('gbr', 'TR', 'Truro', null, null),
('gbr', 'TS', 'Cleveland', null, null),
('gbr', 'TW', 'Twickenham', null, null),
('gbr', 'UB', 'Southall', null, null),
('gbr', 'W', 'London W', null, null),
('gbr', 'WA', 'Warrington', null, null),
('gbr', 'WC', 'London WC', null, null),
('gbr', 'WD', 'Watford', null, null),
('gbr', 'WF', 'Wakefield', null, null),
('gbr', 'WN', 'Wigan', null, null),
('gbr', 'WR', 'Worcester', null, null),
('gbr', 'WS', 'Walsall', null, null),
('gbr', 'WV', 'Wolverhampton', null, null),
('gbr', 'YO', 'York', null, null),
('gbr', 'ZE', 'Lerwick', null, null);
