INSERT IGNORE INTO wa_region (country_iso3, code, name, fav_sort, region_center) VALUES

('usa', 'AK', 'Alaska', null, null),
('usa', 'AL', 'Alabama', null, null),
('usa', 'AR', 'Arkansas', null, null),
('usa', 'AZ', 'Arizona', null, null),
('usa', 'CA', 'California', null, null),
('usa', 'CO', 'Colorado', null, null),
('usa', 'CT', 'Connecticut', null, null),
('usa', 'DC', 'Washington, D.C.', null, null),
('usa', 'DE', 'Delaware', null, null),
('usa', 'FL', 'Florida', null, null),
('usa', 'GA', 'Georgia State', null, null),
('usa', 'HI', 'Hawaii', null, null),
('usa', 'IA', 'Iowa', null, null),
('usa', 'ID', 'Idaho', null, null),
('usa', 'IL', 'Illinois', null, null),
('usa', 'IN', 'Indiana', null, null),
('usa', 'KS', 'Kansas', null, null),
('usa', 'KY', 'Kentucky', null, null),
('usa', 'LA', 'Louisiana', null, null),
('usa', 'MA', 'Massachusetts', null, null),
('usa', 'MD', 'Maryland', null, null),
('usa', 'ME', 'Maine', null, null),
('usa', 'MI', 'Michigan', null, null),
('usa', 'MN', 'Minnesota', null, null),
('usa', 'MO', 'Missouri', null, null),
('usa', 'MS', 'Mississippi', null, null),
('usa', 'MT', 'Montana', null, null),
('usa', 'NC', 'North Carolina', null, null),
('usa', 'ND', 'North Dakota', null, null),
('usa', 'NE', 'Nebraska', null, null),
('usa', 'NH', 'New Hampshire', null, null),
('usa', 'NJ', 'New Jersey', null, null),
('usa', 'NM', 'New Mexico', null, null),
('usa', 'NV', 'Nevada', null, null),
('usa', 'NY', 'New York', null, null),
('usa', 'OH', 'Ohio', null, null),
('usa', 'OK', 'Oklahoma', null, null),
('usa', 'OR', 'Oregon', null, null),
('usa', 'PA', 'Pennsylvania', null, null),
('usa', 'RI', 'Rhode Island', null, null),
('usa', 'SC', 'South Carolina', null, null),
('usa', 'SD', 'South Dakota', null, null),
('usa', 'TN', 'Tennessee', null, null),
('usa', 'TX', 'Texas', null, null),
('usa', 'UT', 'Utah', null, null),
('usa', 'VA', 'Virginia', null, null),
('usa', 'VT', 'Vermont', null, null),
('usa', 'WA', 'Washington', null, null),
('usa', 'WI', 'Wisconsin', null, null),
('usa', 'WV', 'West Virginia', null, null),
('usa', 'WY', 'Wyoming', null, null),

('can', 'AB', 'Alberta', null, null),
('can', 'BC', 'British Columbia', null, null),
('can', 'MB', 'Manitoba', null, null),
('can', 'NB', 'New Brunswick', null, null),
('can', 'NL', 'Newfoundland and Labrador', null, null),
('can', 'NS', 'Nova Scotia', null, null),
('can', 'ON', 'Ontario', null, null),
('can', 'PE', 'Prince Edward Island', null, null),
('can', 'QC', 'Quebec', null, null),
('can', 'SK', 'Saskatchewan', null, null),
('can', 'NT', 'Northwest Territories', null, null),
('can', 'YT', 'Yukon', null, null),
('can', 'NU', 'Nunavut', null, null),

('rus', '01', 'Адыгея республика', null, null),
('rus', '04', 'Алтай республика', null, null),
('rus', '22', 'Алтайский край', null, null),
('rus', '28', 'Амурская область', null, null),
('rus', '29', 'Архангельская область', null, null),
('rus', '30', 'Астраханская область', null, null),
('rus', '02', 'Башкортостан республика', null, null),
('rus', '31', 'Белгородская область', null, null),
('rus', '32', 'Брянская область', null, null),
('rus', '03', 'Бурятия республика', null, null),
('rus', '33', 'Владимирская область', null, null),
('rus', '34', 'Волгоградская область', null, null),
('rus', '35', 'Вологодская область', null, null),
('rus', '36', 'Воронежская область', null, null),
('rus', '05', 'Дагестан республика', null, null),
('rus', '79', 'Еврейская автономная область', null, null),
('rus', '75', 'Забайкальский край', null, null),
('rus', '37', 'Ивановская область', null, null),
('rus', '06', 'Ингушетия республика', null, null),
('rus', '38', 'Иркутская область', null, null),
('rus', '07', 'Кабардино-Балкарская республика', null, null),
('rus', '09', 'Карачаево-Черкесская республика', null, null),
('rus', '39', 'Калининградская область', null, null),
('rus', '08', 'Калмыкия республика', null, null),
('rus', '40', 'Калужская область', null, null),
('rus', '41', 'Камчатский край', null, null),
('rus', '10', 'Карелия республика', null, null),
('rus', '42', 'Кемеровская область', null, null),
('rus', '43', 'Кировская область', null, null),
('rus', '11', 'Коми республика', null, null),
('rus', '44', 'Костромская область', null, null),
('rus', '23', 'Краснодарский край', null, null),
('rus', '24', 'Красноярский край', null, null),
('rus', '91', 'Крым республика', null, null),
('rus', '45', 'Курганская область', null, null),
('rus', '46', 'Курская область', null, null),
('rus', '47', 'Ленинградская область', null, null),
('rus', '48', 'Липецкая область', null, null),
('rus', '49', 'Магаданская область', null, null),
('rus', '12', 'Марий Эл республика', null, null),
('rus', '50', 'Московская область', null, null),
('rus', '77', 'Москва', null, 'Москва'),
('rus', '13', 'Мордовия республика', null, null),
('rus', '51', 'Мурманская область', null, null),
('rus', '83', 'Ненецкий автономный округ', null, null),
('rus', '52', 'Нижегородская область', null, null),
('rus', '53', 'Новгородская область', null, null),
('rus', '54', 'Новосибирская область', null, null),
('rus', '55', 'Омская область', null, null),
('rus', '56', 'Оренбургская область', null, null),
('rus', '57', 'Орловская область', null, null),
('rus', '58', 'Пензенская область', null, null),
('rus', '59', 'Пермский край', null, null),
('rus', '25', 'Приморский край', null, null),
('rus', '60', 'Псковская область', null, null),
('rus', '61', 'Ростовская область', null, null),
('rus', '62', 'Рязанская область', null, null),
('rus', '63', 'Самарская область', null, null),
('rus', '78', 'Санкт-Петербург', null, 'Санкт-Петербург'),
('rus', '64', 'Саратовская область', null, null),
('rus', '14', 'Саха (Якутия) республика', null, null),
('rus', '65', 'Сахалинская область', null, null),
('rus', '66', 'Свердловская область', null, null),
('rus', '92', 'Севастополь', null, 'Севастополь'),
('rus', '15', 'Северная Осетия-Алания', null, null),
('rus', '67', 'Смоленская область', null, null),
('rus', '26', 'Ставропольский край', null, null),
('rus', '68', 'Тамбовская область', null, null),
('rus', '16', 'Татарстан республика', null, null),
('rus', '69', 'Тверская область', null, null),
('rus', '70', 'Томская область', null, null),
('rus', '71', 'Тульская область', null, null),
('rus', '72', 'Тюменская область', null, null),
('rus', '17', 'Тыва республика', null, null),
('rus', '18', 'Удмуртская республика', null, null),
('rus', '73', 'Ульяновская область', null, null),
('rus', '27', 'Хабаровский край', null, null),
('rus', '19', 'Хакасия республика', null, null),
('rus', '86', 'Ханты-Мансийский-Югра автономный округ', null, null),
('rus', '74', 'Челябинская область', null, null),
('rus', '20', 'Чеченская республика', null, null),
('rus', '21', 'Чувашская республика', null, null),
('rus', '87', 'Чукотский автономный округ', null, null),
('rus', '89', 'Ямало-Ненецкий автономный округ', null, null),
('rus', '76', 'Ярославская область', null, null),

('ukr', '01', 'Автономна Республіка Крим', null, null),
('ukr', '02', 'Вінницька область', null, null),
('ukr', '03', 'Волинська область', null, null),
('ukr', '04', 'Дніпропетровська область', null, null),
('ukr', '05', 'Донецька область', null, null),
('ukr', '06', 'Житомирська область', null, null),
('ukr', '07', 'Закарпатська область', null, null),
('ukr', '08', 'Запорізька область', null, null),
('ukr', '09', 'Івано-Франківська область', null, null),
('ukr', '10', 'Київська область', null, null),
('ukr', '11', 'місто Київ', null, null),
('ukr', '12', 'Кіровоградська область', null, null),
('ukr', '13', 'Луганська область', null, null),
('ukr', '14', 'Львівська область', null, null),
('ukr', '15', 'Миколаївська область', null, null),
('ukr', '16', 'Одеська область', null, null),
('ukr', '17', 'Полтавська область', null, null),
('ukr', '18', 'Рівненська область', null, null),
('ukr', '19', 'Сумська область', null, null),
('ukr', '20', 'Тернопільська область', null, null),
('ukr', '21', 'Харківська область', null, null),
('ukr', '22', 'Херсонська область', null, null),
('ukr', '23', 'Хмельницька область', null, null),
('ukr', '24', 'Черкаська область', null, null),
('ukr', '25', 'Чернігівська область', null, null),
('ukr', '26', 'Чернівецька область', null, null),
('ukr', '27', 'місто Севастополь', null, 'Севастополь');
