// plugins
if(!RedactorPlugins)var RedactorPlugins={};
// fontcolor
RedactorPlugins.fontcolor=function(){return{init:function(){for(var b="#ffffff #000000 #eeece1 #1f497d #4f81bd #c0504d #9bbb59 #8064a2 #4bacc6 #f79646 #ffff00 #f2f2f2 #7f7f7f #ddd9c3 #c6d9f0 #dbe5f1 #f2dcdb #ebf1dd #e5e0ec #dbeef3 #fdeada #fff2ca #d8d8d8 #595959 #c4bd97 #8db3e2 #b8cce4 #e5b9b7 #d7e3bc #ccc1d9 #b7dde8 #fbd5b5 #ffe694 #bfbfbf #3f3f3f #938953 #548dd4 #95b3d7 #d99694 #c3d69b #b2a2c7 #b7dde8 #fac08f #f2c314 #a5a5a5 #262626 #494429 #17365d #366092 #953734 #76923c #5f497a #92cddc #e36c09 #c09100 #7f7f7f #0c0c0c #1d1b10 #0f243e #244061 #632423 #4f6128 #3f3151 #31859b #974806 #7f6000 #880000 #aa0000 #cc0000 #ff0000 #ff0055 #ff0088 #ff00aa #ff00cc #ff00ff #cc00ff #aa00ff #8800ff #7700cc #5500aa #000088 #0000aa #0000cc #0000ff #0044ff #0077ff #0099ff #00bbff #00ddff #00ffff #005533 #008833 #00aa33 #00aa00 #00cc00 #00ee00 #00ff00 #88ff00 #bbff00 #ddff00 #ffff00 #ffee00 #ffdd00 #ffbb00 #ff9900 #ff8800 #ff6600 #ff4400 #ee1100 #cc0000".split(" "),
c=["fontcolor","backcolor"],a=0;2>a;a++){var d=c[a],e=this.button.add(d,this.lang.get(d)),e=this.button.addDropdown(e);e.width(242);this.fontcolor.buildPicker(e,d,b)}},buildPicker:function(b,c,a){var d="backcolor"==c?"background-color":"color";c=a.length;for(var e=this,k=function(a){a.preventDefault();e.fontcolor.set($(this).data("rule"),$(this).attr("rel"))},f=0;f<c;f++){var h=a[f],g=$('<a rel="'+h+'" data-rule="'+d+'" href="#" style="float: left; font-size: 0; border: 2px solid #fff; padding: 0; margin: 0; width: 22px; height: 22px;"></a>');
g.css("background-color",h);g.on("click",k);b.append(g)}a=$('<a href="#" style="display: block; clear: both; padding: 5px; font-size: 12px; line-height: 1;"></a>').html(this.lang.get("none"));a.on("click",$.proxy(function(a){a.preventDefault();this.fontcolor.remove(d)},this));b.append(a)},set:function(b,c){this.inline.format("span","style",b+": "+c+";")},remove:function(b){this.inline.removeStyleRule(b)}}};
// fontsize
$.Redactor.opts.langs['en']['change_font_size'] = 'Change font size';
$.Redactor.opts.langs['en']['remove_font_size'] = 'Remove font size';
RedactorPlugins.fontsize=function(){return{init:function(){var a=this,b={};$.each([8,9,10,11,12,14,16,18,20,24,28,30,32,36,42,48],function(c,d){b["s"+c]={title:d+"px",func:function(){a.fontsize.set(d)}}});b.remove={title:this.opts.curLang.remove_font_size,func:a.fontsize.reset};var c=this.button.add("fontsize",this.opts.curLang.change_font_size);this.button.addDropdown(c,b)},set:function(a){this.inline.format("span","style","font-size: "+a+"px;")},reset:function(){this.inline.removeStyleRule("font-size")}}};
// fontfamily
$.Redactor.opts.langs['en']['change_font_family'] = 'Change font family';
$.Redactor.opts.langs['en']['remove_font_family'] = 'Remove font';
RedactorPlugins.fontfamily=function(){return{init:function(){var a=this,b={};$.each("Arial;Helvetica;Georgia;Tahoma;Times New Roman;Trebuchet MS;Verdana;Monospace".split(";"),function(c,d){b["s"+c]={title:d,func:function(){a.fontfamily.set(d)}}});b.remove={title:this.opts.curLang.remove_font_family,func:a.fontfamily.reset};var c=this.button.add("fontfamily",this.opts.curLang.change_font_family);this.button.addDropdown(c,b)},set:function(a){this.inline.format("span","style","font-family:"+a+";")},
reset:function(){this.inline.removeStyleRule("font-family")}}};
// table
RedactorPlugins.table=function(){return{getTemplate:function(){return String()+'<section id="redactor-modal-table-insert"><label>'+this.lang.get("rows")+'</label><input type="text" size="5" value="2" id="redactor-table-rows" /><label>'+this.lang.get("columns")+'</label><input type="text" size="5" value="3" id="redactor-table-columns" /></section>'},init:function(){var a={};a.insert_table={title:this.lang.get("insert_table"),func:this.table.show};a.insert_row_above={title:this.lang.get("insert_row_above"),
func:this.table.addRowAbove};a.insert_row_below={title:this.lang.get("insert_row_below"),func:this.table.addRowBelow};a.insert_column_left={title:this.lang.get("insert_column_left"),func:this.table.addColumnLeft};a.insert_column_right={title:this.lang.get("insert_column_right"),func:this.table.addColumnRight};a.add_head={title:this.lang.get("add_head"),func:this.table.addHead};a.delete_head={title:this.lang.get("delete_head"),func:this.table.deleteHead};a.delete_column={title:this.lang.get("delete_column"),
func:this.table.deleteColumn};a.delete_row={title:this.lang.get("delete_row"),func:this.table.deleteRow};a.delete_table={title:this.lang.get("delete_table"),func:this.table.deleteTable};this.observe.addButton("td","table");this.observe.addButton("th","table");var b=this.button.addBefore("link","table",this.lang.get("table"));this.button.addDropdown(b,a)},show:function(){this.modal.addTemplate("table",this.table.getTemplate());this.modal.load("table",this.lang.get("insert_table"),300);this.modal.createCancelButton();
this.modal.createActionButton(this.lang.get("insert")).on("click",this.table.insert);this.selection.save();this.modal.show();$("#redactor-table-rows").focus()},insert:function(){var a=$("#redactor-table-rows").val(),b=$("#redactor-table-columns").val(),c=$("<div>"),d=Math.floor(99999*Math.random()),f=$('<table id="table'+d+'"><tbody></tbody></table>'),e,h,g,k;for(e=0;e<a;e++){h=$("<tr>");for(g=0;g<b;g++)k=$("<td>"+this.opts.invisibleSpace+"</td>"),0===e&&0===g&&k.append(this.selection.getMarker()),
$(h).append(k);f.append(h)}c.append(f);a=c.html();this.modal.close();this.selection.restore();this.table.getTable()||(this.buffer.set(),(b=this.selection.getBlock()||this.selection.getCurrent())&&"BODY"!=b.tagName?("LI"==b.tagName&&(b=$(b).closest("ul, ol")),$(b).after(a)):this.insert.html(a),this.selection.restore(),d=this.$editor.find("#table"+d),this.opts.linebreaks||!this.utils.browser("mozilla")&&!this.utils.browser("msie")||0===d.next().length&&d.after(this.opts.emptyHtml),this.observe.buttons(),
d.find("span.redactor-selection-marker").remove(),d.removeAttr("id"),this.code.sync(),this.core.setCallback("insertedTable",d))},getTable:function(){var a=$(this.selection.getParent()).closest("table");return this.utils.isRedactorParent(a)&&0!==a.size()?a:!1},restoreAfterDelete:function(a){this.selection.restore();a.find("span.redactor-selection-marker").remove();this.code.sync()},deleteTable:function(){var a=this.table.getTable();if(a){this.buffer.set();var b=a.next();this.opts.linebreaks||0===b.length?
this.caret.setAfter(a):this.caret.setStart(b);a.remove();this.code.sync()}},deleteRow:function(){var a=this.table.getTable();if(a){var b=$(this.selection.getCurrent());this.buffer.set();var b=b.closest("tr"),c=b.prev().length?b.prev():b.next();c.length&&(c=c.children("td, th").first(),c.length&&c.prepend(this.selection.getMarker()));b.remove();this.table.restoreAfterDelete(a)}},deleteColumn:function(){var a=this.table.getTable();if(a){this.buffer.set();var b=$(this.selection.getCurrent()).closest("td, th")[0].cellIndex;
a.find("tr").each($.proxy(function(a,d){var f=$(d),e=0>b-1?b+1:b-1;0===a&&f.find("td, th").eq(e).prepend(this.selection.getMarker());f.find("td, th").eq(b).remove()},this));this.table.restoreAfterDelete(a)}},addHead:function(){var a=this.table.getTable();if(a)if(this.buffer.set(),0!==a.find("thead").size())this.table.deleteHead();else{var b=a.find("tr").first().clone();b.find("td").html(this.opts.invisibleSpace);$thead=$("<thead></thead>").append(b);a.prepend($thead);this.code.sync()}},deleteHead:function(){var a=
this.table.getTable();a&&(a=a.find("thead"),0!==a.size()&&(this.buffer.set(),a.remove(),this.code.sync()))},addRowAbove:function(){this.table.addRow("before")},addRowBelow:function(){this.table.addRow("after")},addColumnLeft:function(){this.table.addColumn("before")},addColumnRight:function(){this.table.addColumn("after")},addRow:function(a){if(this.table.getTable()){this.buffer.set();var b=$(this.selection.getCurrent()).closest("tr"),c=b.clone();c.find("th").replaceWith(function(){var a=$("<td>");
a[0].attributes=this.attributes;return a.append($(this).contents())});c.find("td").html(this.opts.invisibleSpace);"after"==a?b.after(c):b.before(c);this.code.sync()}},addColumn:function(a){var b=this.table.getTable();if(b){var c=0,d=$(this.selection.getCurrent());this.buffer.set();var f=d.closest("tr"),e=d.closest("td, th");f.find("td, th").each($.proxy(function(a,b){$(b)[0]===e[0]&&(c=a)},this));b.find("tr").each($.proxy(function(b,d){var e=$(d).find("td, th").eq(c),f=e.clone();f.html(this.opts.invisibleSpace);
"after"==a?e.after(f):e.before(f)},this));this.code.sync()}}}};
// video
RedactorPlugins.video=function(){return{reUrlYoutube:/https?:\/\/(?:[0-9A-Z-]+\.)?(?:youtu\.be\/|youtube\.com\S*[^\w\-\s])([\w\-]{11})(?=[^\w\-]|$)(?![?=&+%\w.-]*(?:['"][^<>]*>|<\/a>))[?=&+%\w.-]*/ig,reUrlVimeo:/https?:\/\/(www\.)?vimeo.com\/(\d+)($|\/)/,getTemplate:function(){return String()+'<section id="redactor-modal-video-insert"><label>'+this.lang.get("video_html_code")+'</label><textarea id="redactor-insert-video-area" style="height: 160px;"></textarea></section>'},init:function(){var a=this.button.addAfter("image",
"video",this.lang.get("video"));this.button.addCallback(a,this.video.show)},show:function(){this.modal.addTemplate("video",this.video.getTemplate());this.modal.load("video",this.lang.get("video"),700);this.modal.createCancelButton();this.modal.createActionButton(this.lang.get("insert")).on("click",this.video.insert);this.selection.save();this.modal.show();$("#redactor-insert-video-area").focus()},insert:function(){var a=$("#redactor-insert-video-area").val();a.match(/<iframe|<video/gi)||(a=this.clean.stripTags(a),
a.match(this.video.reUrlYoutube)?a=a.replace(this.video.reUrlYoutube,'<iframe style="width: 500px; height: 281px;" src="//www.youtube.com/embed/$1" frameborder="0" allowfullscreen></iframe>'):a.match(this.video.reUrlVimeo)&&(a=a.replace(this.video.reUrlVimeo,'<iframe style="width: 500px; height: 281px;" src="//player.vimeo.com/video/$2" frameborder="0" allowfullscreen></iframe>')));this.selection.restore();this.modal.close();var b=this.selection.getBlock()||this.selection.getCurrent();b?$(b).after(a):
this.insert.html(a);this.code.sync()}}};
