<?php

return [
    0 => [
        'tariffId' => 1402,
        'tariffName' => NULL,
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 781.03868,
            'deliveryForCustomer' => 59.94,
        ],
        'delivery' => [
            'partner' => [
                'id' => 48,
                'code' => 'Стриж',
                'name' => 'Стриж',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2006792/Strizh_1581004726.svg/orig',
            ],
            'type' => 'COURIER',
            'calculatedDeliveryDateMin' => '2020-09-25',
            'calculatedDeliveryDateMax' => '2020-09-28',
            'courierSchedule' => [
                'locationId' => 10887,
                'schedule' => [
                    0 => [
                        'id' => NULL,
                        'timeFrom' => '09:00:00',
                        'timeTo' => '22:00:00',
                    ],
                ],
            ],
        ],
        'pickupPointIds' => NULL,
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 48,
                    'code' => 'Стриж',
                    'name' => 'Стриж',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2006792/Strizh_1581004726.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 500.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 59.94,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 375.0,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 221.09868,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [
            0 => 'OPTIMAL',
        ],
    ],
    1 => [
        'tariffId' => 3999,
        'tariffName' => NULL,
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 446.03868,
            'deliveryForCustomer' => 59.94,
        ],
        'delivery' => [
            'partner' => [
                'id' => 51,
                'code' => 'СДЭК',
                'name' => 'СДЭК',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2006792/CDEK_1581004726.svg/orig',
            ],
            'type' => 'PICKUP',
            'calculatedDeliveryDateMin' => '2020-09-26',
            'calculatedDeliveryDateMax' => '2020-09-26',
            'courierSchedule' => NULL,
        ],
        'pickupPointIds' => [
            0 => 10000007373,
        ],
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 51,
                    'code' => 'СДЭК',
                    'name' => 'СДЭК',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2006792/CDEK_1581004726.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 165.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 59.94,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 123.75,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 221.09868,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    2 => [
        'tariffId' => 100004,
        'tariffName' => 'СДЭК МСК',
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 1027.03868,
            'deliveryForCustomer' => 59.94,
        ],
        'delivery' => [
            'partner' => [
                'id' => 51,
                'code' => 'СДЭК',
                'name' => 'СДЭК',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2006792/CDEK_1581004726.svg/orig',
            ],
            'type' => 'COURIER',
            'calculatedDeliveryDateMin' => '2020-09-26',
            'calculatedDeliveryDateMax' => '2020-09-26',
            'courierSchedule' => [
                'locationId' => 10887,
                'schedule' => [
                    0 => [
                        'id' => 21294424,
                        'timeFrom' => '09:00:00',
                        'timeTo' => '18:00:00',
                    ],
                    1 => [
                        'id' => 21294431,
                        'timeFrom' => '09:00:00',
                        'timeTo' => '22:00:00',
                    ],
                ],
            ],
        ],
        'pickupPointIds' => NULL,
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 51,
                    'code' => 'СДЭК',
                    'name' => 'СДЭК',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2006792/CDEK_1581004726.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 746.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 59.94,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 559.5,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 221.09868,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    3 => [
        'tariffId' => 100002,
        'tariffName' => 'Boxberry ПВЗ из МСК',
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 488.03868,
            'deliveryForCustomer' => 59.94,
        ],
        'delivery' => [
            'partner' => [
                'id' => 106,
                'code' => 'Boxberry',
                'name' => 'Боксберри',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2003566/Boxberry_1581004726.svg/orig',
            ],
            'type' => 'PICKUP',
            'calculatedDeliveryDateMin' => '2020-09-27',
            'calculatedDeliveryDateMax' => '2020-09-28',
            'courierSchedule' => NULL,
        ],
        'pickupPointIds' => [
            0 => 10001566887,
        ],
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 106,
                    'code' => 'Boxberry',
                    'name' => 'Боксберри',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/2003566/Boxberry_1581004726.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 207.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 59.94,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 155.25,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 221.09868,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    4 => [
        'tariffId' => 100041,
        'tariffName' => 'ПЭК МСК — Курьерка',
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 1022.03868,
            'deliveryForCustomer' => 59.94,
        ],
        'delivery' => [
            'partner' => [
                'id' => 9,
                'code' => 'ПЭК',
                'name' => 'ПЭК',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/1985666/PEK_1581004726.svg/orig',
            ],
            'type' => 'COURIER',
            'calculatedDeliveryDateMin' => '2020-09-28',
            'calculatedDeliveryDateMax' => '2020-09-28',
            'courierSchedule' => [
                'locationId' => 10887,
                'schedule' => [
                    0 => [
                        'id' => 22310513,
                        'timeFrom' => '10:00:00',
                        'timeTo' => '18:00:00',
                    ],
                ],
            ],
        ],
        'pickupPointIds' => NULL,
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 9,
                    'code' => 'ПЭК',
                    'name' => 'ПЭК',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mds.yandex.net/get-lms/1985666/PEK_1581004726.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 741.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 59.94,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 555.75,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 221.09868,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    5 => [
        'tariffId' => 100005,
        'tariffName' => 'Почта России МСК — Посылка нестандартная',
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 989.38098,
            'deliveryForCustomer' => 409.59,
        ],
        'delivery' => [
            'partner' => [
                'id' => 1003375,
                'code' => 'Beta',
                'name' => 'Почта России',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
            ],
            'type' => 'POST',
            'calculatedDeliveryDateMin' => '2020-10-03',
            'calculatedDeliveryDateMax' => '2020-10-05',
            'courierSchedule' => NULL,
        ],
        'pickupPointIds' => [
            0 => 10001015980,
            1 => 10001015983,
        ],
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 1003375,
                    'code' => 'Beta',
                    'name' => 'Почта России',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 351.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 409.59,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 263.25,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 228.79098,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    6 => [
        'tariffId' => 100005,
        'tariffName' => 'Почта России МСК — Посылка нестандартная',
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 989.38098,
            'deliveryForCustomer' => 409.59,
        ],
        'delivery' => [
            'partner' => [
                'id' => 1003375,
                'code' => 'Beta',
                'name' => 'Почта России',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
            ],
            'type' => 'POST',
            'calculatedDeliveryDateMin' => '2020-10-03',
            'calculatedDeliveryDateMax' => '2020-10-06',
            'courierSchedule' => NULL,
        ],
        'pickupPointIds' => [
            0 => 10001015985,
        ],
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 1003375,
                    'code' => 'Beta',
                    'name' => 'Почта России',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 351.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 409.59,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 263.25,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 228.79098,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    7 => [
        'tariffId' => 4386,
        'tariffName' => NULL,
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 1138.38098,
            'deliveryForCustomer' => 409.59,
        ],
        'delivery' => [
            'partner' => [
                'id' => 1003375,
                'code' => 'Beta',
                'name' => 'Почта России',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
            ],
            'type' => 'POST',
            'calculatedDeliveryDateMin' => '2020-10-05',
            'calculatedDeliveryDateMax' => '2020-10-08',
            'courierSchedule' => NULL,
        ],
        'pickupPointIds' => [
            0 => 10001015980,
            1 => 10001015983,
        ],
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 1003375,
                    'code' => 'Beta',
                    'name' => 'Почта России',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 500.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 409.59,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 375.0,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 228.79098,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
    8 => [
        'tariffId' => 4386,
        'tariffName' => NULL,
        'cost' => [
            'delivery' => 0.0,
            'deliveryForSender' => 1138.38098,
            'deliveryForCustomer' => 409.59,
        ],
        'delivery' => [
            'partner' => [
                'id' => 1003375,
                'code' => 'Beta',
                'name' => 'Почта России',
                'partnerType' => 'DELIVERY',
                'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
            ],
            'type' => 'POST',
            'calculatedDeliveryDateMin' => '2020-10-06',
            'calculatedDeliveryDateMax' => '2020-10-08',
            'courierSchedule' => NULL,
        ],
        'pickupPointIds' => [
            0 => 10001015985,
        ],
        'shipments' => [
            0 => [
                'date' => '2020-09-24',
                'type' => 'WITHDRAW',
                'partner' => [
                    'id' => 1003375,
                    'code' => 'Beta',
                    'name' => 'Почта России',
                    'partnerType' => 'DELIVERY',
                    'logoUrl' => 'http://avatars.mdst.yandex.net/get-lms/70086/post.svg/orig',
                ],
                'warehouse' => NULL,
                'settingsDefault' => true,
                'alreadyExists' => false,
            ],
        ],
        'services' => [
            0 => [
                'name' => 'Доставка',
                'code' => 'DELIVERY',
                'cost' => 500.0,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            1 => [
                'name' => 'Услуга «Объявленная ценность»',
                'code' => 'INSURANCE',
                'cost' => 409.59,
                'customerPay' => true,
                'enabledByDefault' => true,
            ],
            2 => [
                'name' => 'Возврат',
                'code' => 'RETURN',
                'cost' => 375.0,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            3 => [
                'name' => 'Сортировка возврата',
                'code' => 'RETURN_SORT',
                'cost' => 20,
                'customerPay' => false,
                'enabledByDefault' => false,
            ],
            4 => [
                'name' => 'Вознаграждение за перечисление денежных средств',
                'code' => 'CASH_SERVICE',
                'cost' => 228.79098,
                'customerPay' => false,
                'enabledByDefault' => true,
            ],
        ],
        'tags' => [],
    ],
];
