(function(a){var e=2,b=window,d=a(b),h=!1,c={url:"",target:".b-stream",count:10,scroll:null,stop:null,bottom_distance:80,content_distance:120,auto:!0,beforeLoad:null,afterLoad:null,renderContent:null,paging_selector:null,pageless_wrapper:null},k=function(){var b=c.pageless_wrapper;b.show();c.paging_selector&&a(c.paging_selector).hide();b.find("a.pageless-link").live("click",function(){i(!0);return!1});d.bind("scroll.pageless resize.pageless",i).trigger("scroll.pageless")},g=function(){d.unbind(".pageless");
c.stop&&"function"==typeof c.stop&&c.stop.apply(this,[])},l=function(){var d=c.pageless_wrapper,b=d.find(".pageless-link"),g=d.find(".pageless-progress");g.length?(b.hide(),g.show()):b.replaceWith('<i class="icon16 loading"></i>'+b.text());h=!0;"function"===typeof c.beforeLoad&&c.beforeLoad();a.get(c.url,{page:e++},function(b){var e=b.data?b.data.content:b;if(typeof c.renderContent==="function")c.renderContent(e,a(c.target));else{d.remove();a(c.target).append(e);d=c.pageless_wrapper=a(c.target+" .pageless-wrapper")}c.scroll&&
typeof c.scroll=="function"&&c.scroll.apply(this,[b,c.target]);h=false;typeof c.afterLoad==="function"&&c.afterLoad();i()})},i=function(f){if(e>=parseInt(c.count)+1)g.apply(this,[]);else if(!h){var j=!1;if(!0===f)j=!0;else if(c.auto){if(!(f=(b===window?a(document).height()-d.scrollTop()-d.height():d[0].scrollHeight-d.scrollTop()-d.height())<c.bottom_distance))f=c.pageless_wrapper,f=f.length?a(window).height()-f.position().top+d.scrollTop():0,f=f>c.content_distance;j=f}j&&l.apply(this,[])}};a.pageless=
function(d,b){("start"==d||"refresh"==d)&&k.apply(this,[]);"url"==d&&(c.url=b);a.isPlainObject(d)&&(a.extend(c,d),null===c.pageless_wrapper?c.pageless_wrapper=a(c.target+" .pageless-wrapper"):!1===c.pageless_wrapper&&(c.pageless_wrapper=a()),k.apply(this,[]))}})(jQuery);(function(a){a.wa_blog.stream={management:!1,options:{pageless:{}},init:function(e){this.options=a.extend(this.options,e);var b=this;a("a[href=#manage]").click(function(a){return b.manageHandler.apply(b,[this,a])});a(".js-manage-done").click(function(a){return b.manageCompleteHandler.apply(b,[this,a])});a("input.search").keydown(function(d){if(13==d.keyCode){var d=a(this).val(),b=location.search.match(/[&\?](text=.*?&|text=.*)/);b?(b=b[1],d?(d="&"==b.substr(-1)?"text="+encodeURIComponent(d)+"&":"text="+
encodeURIComponent(d),location.search=location.search.replace(b,d)):("&"!=b.substr(-1)&&(b="[&?]"+b),location.search=location.search.replace(RegExp(b),""))):d&&(location.search+=(location.search?"&":"?")+"text="+encodeURIComponent(d));return!1}});a("input.blog-post-checkbox").live("click",function(a){return b.counterHandler.apply(b,[this,a])});a("#postdelete-dialog input[type=button]").click(function(a){return b.deleteHandler.apply(b,[this,a])});a('#postmove-dialog input[type="button"]').click(function(a){return b.moveHandler.apply(b,
[this,a])});e={scroll:function(){a.wa_blog.common.onContentUpdate()}};e=a.extend(!0,e,b.options.pageless);a.pageless(e)},manageHandler:function(){a("#blog-stream-primary-menu").hide();a("#blog-stream-manage-menu").show();this.management=!0;this.onContentUpdate();return!1},manageCompleteHandler:function(){this.management=!1;a("#blog-stream-manage-menu").hide();a("#blog-stream-primary-menu").show();a(".b-post.js-managed").each(function(){a(this).removeClass("js-managed");a(this).find("h3:hidden").show();
a(this).find("h3:first").hide();a(this).find(".b-post-body:hidden, .profile.image20px:hidden").fadeIn()});return!1},counterHandler:function(){a(".js-blog-selected-posts-counter").text(a("input.blog-post-checkbox:checked").length)},moveHandler:function(e){var b=[];a("input.blog-post-checkbox:checked").each(function(){b.push(a(this).val())});var d=a("#postmove-dialog :input[name=blog_id]").val();b.length?(a(e).attr("disabled",!0).after('<i class="icon16 loading"></i>'),a.ajax({url:"?module=post&action=move",
data:{id:b,blog:d},type:"post",dataType:"json",success:function(b){var c=!1;if("ok"==b.status)for(var d in b.data.moved){var e=a("#b-post-"+b.data.moved[d]);e.length&&(c=!0,e.animate({opacity:0.1,height:0},200,function(){e.remove()}))}a.wa_blog.stream.counterHandler();c?window.location.reload():(a("#postmove-dialog .icon16.loading").remove(),a("#postmove-dialog input[type=button]:disabled").removeAttr("disabled"),a.wa_blog.dialogs.close("postmove"))},error:function(){a("#postmove-dialog .icon16.loading").remove();
a("#postmove-dialog input[type=button]:disabled").removeAttr("disabled");a.wa_blog.dialogs.close("postmove")}})):a.wa_blog.dialogs.close("postmove")},deleteHandler:function(e){var b=[];a("input.blog-post-checkbox:checked").each(function(){b.push(a(this).val())});b.length?(a(e).attr("disabled",!0).after('<i class="icon16 loading"></i>'),a.ajax({url:"?module=post&action=delete",data:{id:b},type:"post",dataType:"json",success:function(b){"ok"==b.status&&b.data.deleted?window.location.reload():(a("#postdelete-dialog .icon16.loading").remove(),
a("#postdelete-dialog input[type=button]:disabled").removeAttr("disabled"),a.wa_blog.dialogs.close("postdelete"),a.wa_blog.stream.counterHandler())},error:function(){a("#postdelete-dialog .icon16.loading").remove();a("#postdelete-dialog input[type=button]:disabled").removeAttr("disabled");a.wa_blog.dialogs.close("postdelete");a.wa_blog.stream.counterHandler()}})):a.wa_blog.dialogs.close("postdelete")},onContentUpdate:function(){if(this.management){var e=this,b=!1;a(".b-post-body:visible, .profile.image20px:visible").hide();
a(".b-post").each(function(){a(this).hasClass("js-managed")||(a(this).find("h3:visible").hide(),a(this).find("h3:first").show(),b=!0,a(this).addClass("js-managed"))});b&&setTimeout(function(){a(e.options.pageless.target).trigger("scroll.pageless")},100)}}}})(jQuery);
