(function ($)
{
$.Redactor.opts.langs['ru'] = {
"format": "Формат",
"image": "Картинка",
"file": "Файл",
"link": "Ссылка",
"bold": "Полужирный",
"italic": "Курсив",
"deleted": "Зачеркнутый",
"underline": "Подчеркнутый",
"bold-abbr": "B",
"italic-abbr": "I",
"deleted-abbr": "S",
"underline-abbr": "U",
"lists": "Списки",
"link-insert": "Вставить ссылку",
"link-edit": "Редактировать ссылку",
"link-in-new-tab": "Открыть ссылку в новом табе",
"unlink": "Удалить ссылку",
"cancel": "Отменить",
"close": "Закрыть",
"insert": "Вставить",
"save": "Сохранить",
"delete": "Удалить",
"text": "Текст",
"edit": "Редактировать",
"general": "Общие",
"title": "Всплывающая подсказка",
"paragraph": "Обычный текст",
"quote": "Цитата",
"code": "Код",
"heading1": "Заголовок 1",
"heading2": "Заголовок 2",
"heading3": "Заголовок 3",
"heading4": "Заголовок 4",
"heading5": "Заголовок 5",
"heading6": "Заголовок 6",
"filename": "Имя файла",
"optional": "необязательно",
"unorderedlist": "Ненумерованный список",
"orderedlist": "Нумерованный список",
"outdent": "Убрать отступ",
"indent": "Добавить отступ",
"horizontalrule": "Линия",
"upload": "Загрузить",
"upload-label": "Перетащите файл или ",
"accessibility-help-label": "Редактор форматированного текста",
"caption": "Подпись",
"bulletslist": "Маркеры",
"numberslist": "Нумерация",
"image-position": "Положение",
"none": "Нет",
"left": "Слева",
"right": "Справа",
"center": "По центру",

"style": "Стиль",
"style-marked": "Выделение",
"style-code": "Моноширинный",
"style-sample": "Пример",
"style-variable": "Переменная",
"style-shortcut": "Сокращение",
"style-cite": "Цитата",
"style-sup": "Надстрочный",
"style-sub": "Подстрочный",

"table": "Таблица",
"insert-table": "Добавить таблицу",
"insert-row-above": "Вставить строку сверху",
"insert-row-below": "Вставить строку снизу",
"insert-column-left": "Вставить колонку слева",
"insert-column-right": "Вставить колонку справа",
"add-head": "Добавить заголовок",
"delete-head": "Убрать заголовок",
"delete-column": "Убрать колонку",
"delete-row": "Убрать строку",
"delete-table": "Удалить таблицу",

"align": "Выравнивание",
"align-left": "По левому краю",
"align-center": "По центру",
"align-right": "По правому краю",
"align-justify": "По ширине",

"fontcolor": "Цвет текста",
"fontcolor-highlight": "Фон",
"fontcolor-text": "Текст",
"fontcolor-none": "Убрать",

"fontfamily": "Шрифт",
"fontfamily-remove": "По умолчанию",

"fontsize": "Размер",
"fontsize-remove": "По умолчанию",

"video": "Видео",
"video-html-code": "Код для вставки или ссылка Youtube или Vimeo:",
"code-to-insert": "Код для вставки:",
"blockquote-to-insert": "Цитата для вставки:"

};

})(jQuery);